### ISSUE TITLE
Feature Request: support for multiple package directories?

### ISSUE THREAD

**Issue by MingcongBai** [hughsie/appstream-glib#103]
For example, when I have `/worker/repoA` and `/worker/repoB` to scan and build AppStream data from, how would I handle it so that a single origin XML is produced (instead of having to specify two origins in that case)?

Or is this an undocumented feature that we never know of?

**Comment by hughsie** [comment]
You can just specify the globs on the command line, e.g.

    appstream-builder /worker/repoA/*.rpm /worker/repoB/*.rpm

Does that help? Richard.

**Comment by MingcongBai** [comment]
I did not know that! Thank you!

Might as well update the document for a bit? I am sure happy to do so :-).

Best Regards,
Jeff Bai

(Wait, this is a GitHub issue...)
2016年5月4日 09:09，"Richard Hughes" <notifications@github.com>写道：

**Comment by MingcongBai** [comment]
Thanks. I will close this issue now.
