### ISSUE TITLE
Validation fails for component console-application

### ISSUE THREAD

**Issue by chronitis** [hughsie/appstream-glib#127]
I tried validating (`appstream-util validate-relax --nonet org.test.consoleapp.metainfo.xml`) a console application metainfo file as per <https://www.freedesktop.org/software/appstream/docs/sect-Metadata-ConsoleApplication.html>

The metainfo file contained

```
<?xml version="1.0" encoding="UTF-8"?>
<component type="console-application">
    <id>org.test.consoleapp</id>
    <metadata_license>MIT</metadata_license>
    <project_license>MIT</project_license>
    <name>ConsoleApp</name>
    <summary>A test application</summary>
    <provides>
        <binary>consoleapp</binary>
    </provides>
</component>
```

This failed with

```
org.test.consoleapp.metainfo.xml: FAILED:
• attribute-invalid     : <id> has invalid type attribute
• markup-invalid        : <id> does not have correct extension for kind
Validation of files failed
```

It appears `as_app_kind_to_string` and friends do not handle this component type and it is treated as unknown.

**Comment by hughsie** [comment]
I think this is fixed in git, thanks @ximion.
