### ISSUE TITLE
Release tarball is not properly configured(?)

### ISSUE THREAD

**Issue by marv** [hughsie/appstream-glib#137]
Is there a particular reason why the tarball doesn't come with a configure script etc. instead requires to generate that first instead of going the usual ./configure && make route?

**Comment by ignatenkobrain** [comment]
```
[brain@x1carbon ~]$ wget https://people.freedesktop.org/~hughsient/appstream-glib/releases/appstream-glib-0.6.3.tar.xz 
--2016-10-05 11:31:27--  https://people.freedesktop.org/~hughsient/appstream-glib/releases/appstream-glib-0.6.3.tar.xz
Resolving people.freedesktop.org (people.freedesktop.org)... 131.252.210.176, 2610:10:20:722:a800:ff:feda:470f
Connecting to people.freedesktop.org (people.freedesktop.org)|131.252.210.176|:443... connected.
HTTP request sent, awaiting response... cd200 OK
Length: 1944512 (1.9M) [application/x-xz]
Saving to: ‘appstream-glib-0.6.3.tar.xz’

appstream-glib-0.6.3.tar.xz                 100%[===========================================================================================>]   1.85M  1.19MB/s    in 1.6s    

2016-10-05 11:31:30 (1.19 MB/s) - ‘appstream-glib-0.6.3.tar.xz’ saved [1944512/1944512]

[brain@x1carbon ~]$ tar xvf appstream-glib-0.6.3.tar.xz 
appstream-glib-0.6.3/
...
appstream-glib-0.6.3/configure
...
```

**Comment by smcv** [comment]
The Github "Releases" page is usually a trap. If the maintainer has not specifically uploaded tarballs that do contain the Autotools-generated files (like the Flatpak maintainer does, <https://github.com/flatpak/flatpak/releases>) then the tarballs on Github's "Releases" page are auto-generated from whatever happens to be in git.

In particular, the auto-generated tarballs will not contain autogenerated files, will not usually match tarballs that the maintainer has released elsewhere (on freedesktop.org in this case), and are not even guaranteed to stay byte-for-byte identical over time (their contents are whatever is produced by the version of `git archive` that happens to be installed on Github servers today).
