### ISSUE TITLE
dconf-CRITICAL **: unable to create directory '/root/.cache/dconf': Read-only file system.  dconf will not work properly.

### ISSUE THREAD

**Issue by LebedevRI** [hughsie/appstream-glib#138]
Hi.

When doing `appstream-util validate` within RO docker, we get some messages:
```
/build/darktable-build/data/darktable.appdata.xml: 
(appstream-util:1687): dconf-CRITICAL **: unable to create directory '/root/.cache/dconf': Read-only file system.  dconf will not work properly.
(appstream-util:1687): dconf-CRITICAL **: unable to create directory '/root/.cache/dconf': Read-only file system.  dconf will not work properly.
(appstream-util:1687): dconf-CRITICAL **: unable to create directory '/root/.cache/dconf': Read-only file system.  dconf will not work properly.
(appstream-util:1687): dconf-CRITICAL **: unable to create directory '/root/.cache/dconf': Read-only file system.  dconf will not work properly.
(appstream-util:1687): dconf-CRITICAL **: unable to create directory '/root/.cache/dconf': Read-only file system.  dconf will not work properly.
OK
```
https://travis-ci.org/darktable-org/darktable/jobs/170078537#L605-L615

It would be nice if it could just work, without attempting to clutter the fs and loudly complaining when it is being refused to do so :)

**Comment by LebedevRI** [comment]
I now realize that this might be the wrong place to report this, but `dpkg -S appstream-util; apt-cache show appstream-util` point to [appstream-glib](http://people.freedesktop.org/~hughsient/appstream-glib/).

**Comment by hughsie** [comment]
I think you probably want to file a bug with GLib or dconf; appstream-glib probably loads the latter automatically, but certainly doesn't use it. Sorry.
