### ISSUE TITLE
appstream_glib  checks for registered desktop environment instead of project group (and maybe should make no check at all)

### ISSUE THREAD

**Issue by carandraug** [hughsie/appstream-glib#140]
The check that validates an appdata file checks that the value of a `project_group` is a registered desktop environment [like so](https://github.com/hughsie/appstream-glib/blob/master/libappstream-glib/as-app.c#L2183):

            /* check value */
            if (priv->trust_flags != AS_APP_TRUST_FLAG_COMPLETE) {
                    if (!as_utils_is_environment_id (project_group)) {
                            priv->problems |= AS_APP_PROBLEM_INVALID_PROJECT_GROUP;
                            return;
                    }
            }

where environment ids comes from a [list of registered desktop environments only](https://github.com/hughsie/appstream-glib/blob/master/libappstream-glib/as-environment-ids.txt):

    # these are registered desktop environments
    GNOME
    KDE
    LXDE
    MATE
    Razor
    ROX
    TDE
    Sugar
    Unity
    XFCE
    EDE
    Cinnamon
    elementary

This has two problems:

1. it does not match the [specs](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html) which say:

> If you include the <project_group/> tag then this identifies your project with a specific upstream umbrella project. Known values include GNOME, KDE, XFCE, MATE and LXDE, although other umbrella projects like Yorba or Mozilla make sense too. 

The specs do not limit `<project_group>` to desktop environment, any project group is valid.

2. this is not so much an issue but I would argue that a whitelist of valid projects groups is not the right solution for this since there is a lot of project groups.

Please see related issues #90 where it is discussed that a whitelist does not seem like a good solution and also that project_group is not limited 

@ximion  [said](https://github.com/hughsie/appstream-glib/issues/90#issuecomment-226827356):
> So, I would argue that asglib restricting the values in project_group is wrong, and that the docs are correct, especially since other implementations handle it this way.

**Comment by hughsie** [comment]
We use the project_group in gnome-software as an enumerated type, so I'm not sure this makes sense to change. I think `<developer_name>` is probably what you want to use.

**Comment by carandraug** [comment]
> We use the project_group in gnome-software as an enumerated type, so I'm not sure this makes sense to change.

I'm raising an issue against that very usage type. The whole point of this issue is that it's wrong.  A project group is not a desktop environment.  The specs even mention Mozilla as an example `<project_group>`

> I think <developer_name> is probably what you want to use.

Why would you say that? Nothing on this issue is about the value I want to use.

**Comment by hughsie** [comment]
> I'm raising an issue against that very usage type

Sure, you can do that. Why do you want to use <project_group> rather than <developer_name>?

**Comment by carandraug** [comment]
>> I'm raising an issue against that very usage type

> Sure, you can do that. Why do you want to use <project_group> rather than <developer_name>?

That has nothing to do with this issue. Each has their own purpose and one should be able to use both.

For example, the specs give an example of using "GNOME" in `<project_group>` and "The GNOME Foundation" in `<developer_name>`.  In the same vein, one should be able to have "Mozilla" in `<project_group>` and "The Mozilla Foundation" in `<developer_name>`.

Actually, "Mozilla" is mentioned on the specs as a valid `<project_group>` but because it is not a desktop environment it appears reported as invalid project group. This is what this issue is about. Valid project groups are reported as invalid because a whitelist of desktop environment is being used for validation.
