### ISSUE TITLE
Assertion failed when trying to validate an AppStream appdata file

### ISSUE THREAD

**Issue by AsciiWolf** [hughsie/appstream-glib#145]
I am getting the following failed assertion message when trying to validate [this file](https://raw.githubusercontent.com/csete/gqrx/master/gqrx.appdata.xml):

`$ appstream-util validate-relax gqrx.appdata.xml`
`gqrx.appdata.xml: `
`(appstream-util:2666): GLib-CRITICAL **: g_strstr_len: assertion 'haystack != NULL' failed`
`(appstream-util:2666): GLib-CRITICAL **: g_strstr_len: assertion 'haystack != NULL' failed`
`(appstream-util:2666): GLib-CRITICAL **: g_strstr_len: assertion 'haystack != NULL' failed`
`(appstream-util:2666): GLib-CRITICAL **: g_strstr_len: assertion 'haystack != NULL' failed`
`(appstream-util:2666): GLib-CRITICAL **: g_strstr_len: assertion 'haystack != NULL' failed`
`(appstream-util:2666): GLib-CRITICAL **: g_strstr_len: assertion 'haystack != NULL' failed`
`OK`

`$ appstream-util --version`
`Version:	0.6.6`

**Comment by hughsie** [comment]
I think this is fixed in the recently released 0.6.7.

**Comment by AsciiWolf** [comment]
I can confirm that this issue is fixed in the latest release. Thanks!
