### ISSUE TITLE
Icon rendering between as and asglib differs

### ISSUE THREAD

**Issue by Conan-Kudo** [hughsie/appstream-glib#150]
There are some applications (notably the ones in your as data fail report from elementary) that do not ship an icon in the package. Instead they use a generic icon reference so that the system theme fulfills the icon (see [icon naming spec](https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html)).

This works with AppCenter (which uses @ximion's AppStream), which supports this. However, GNOME Software (which uses your appstream-glib) does not support this, and instead renders nothing.

For now, I believe @decathorpe is modifying packages to ship an icon, but this is against upstream's wishes, and this should be something that works consistently across both AppStream implementations and across all software center applications that use AppStream data. Especially since only your implementation can be used by RPM based distros, and only @ximion's implementation can be used by Debian based distros.

**Comment by hughsie** [comment]
>appstream-glib does not support this, and instead renders nothing

appstream-glib supports stock icons. What's the validation failure for the elementary apps?

Richard.

**Comment by Conan-Kudo** [comment]
@hughsie The issues were all listed in your AppData report: https://dl.fedoraproject.org/pub/alt/screenshots/f26/failed.html

For example, with `screenshot-tool.desktop`, it says "Failed to find icon: Failed to find icon accessories-screenshot, Has no Icon".

Before he started modifying the desktop files and shipping copies of stock icons from elementary-theme to make it not fail, all the pantheon apps did this.

**Comment by hughsie** [comment]
But accessories-screenshot isn't a stock icon... https://github.com/hughsie/appstream-glib/blob/master/libappstream-glib/as-stock-icons.txt

**Comment by ximion** [comment]
@Conan-Kudo @hughsie This is working in AppStream Generator because asgen has a global icon search. Icons are generally processed like:
 * If the icon is a theme icon, do the following:
 * Search for the icon in the package itself (/usr/share/icons/hicolor/...)
 * If it isn't there, search for it in all packages, because the icon might be very high up in the dependency chain
 * If it is still not found, search for it in theme packages
 * If it is still no found, fail

Asgen also considers all icons "stock" and doesn't have a whitelist, meaning that as long as no absolute path is given, the asgen output will have a `<icon type="stock"/>` tag (or an `Icon:\n  stock:` field). The reason is simply because desktop-environments wanted to override icons as they whish, for example KDE wants to give GIMP and Firefox new icons, so as long as the .desktop file supports this, we expose it in the AppStream metadata.

I care a lot for "if installed, the app should look exactly as it was displayed in the SC".

I assume appstream-glib doesn't do one of these things.

**Comment by hughsie** [comment]
So you include the stock icon in the appstream tarball? If you don't then you don't get an icon in gnome-software if elementary-icon-theme isn't already installed, if you do then you're duplicating stock icons from an icon theme that the user may already have installed. It's either stock, or cached, and elementary seems to do something in the middle where it uses a private icon theme and elementary apps then load a stock icon. That's broken IMHO.

**Comment by ximion** [comment]
> So you include the stock icon in the appstream tarball?

Yes

> then you're duplicating stock icons from an icon theme that the user may already have installed

Yes, and I dislike this a lot, but...

> seems to do something in the middle where it uses a private icon theme and elementary apps then load a stock icon

This is the way KDE works as well, and it's a very common practice (one central place to change all icons and the appearance of the whole desktop, ideally a place where designers can commit on their own). So it was either drop the apps and force everyone to adapt, or roll with it for now.

One thing that's on my TODO list is to drop XDG-specified icon names from the icon tarball - with that I will make the assumption that the desktop provides a complete default theme which at least serves all the icon names specified by XDG, which IMHO is a fair assumption to make. I haven't had time to implement this feature yet, though.

**Comment by hughsie** [comment]
> will make the assumption that the desktop provides a complete default theme 

Isn't this what appstream-glib is doing? If the icon is stock then it's expected to be in the users currently installed theme. So stock icons are not shipped in the tarball, and are loaded from the current users theme. I don't think it's valid elementary is just "inventing" stock icon names and I do think it's right to check that stock icon names are in the XDG icon specification to prevent applications doing the wrong thing. The icon naming specification already provides a way for applications to ship a default icon (dropping the various sizes into hicolor) and for the current theme to override these as required, so I don't think we want to re-invent, or re-interpret the wheel here.

**Comment by hughsie** [comment]
I think my call here is that apps should ship their own app icon, and if using a stock icon that icon should be in all the major icon themes (and as-stock-icons.txt).
