### ISSUE TITLE
validation fails for a presumably (?) valid appdata.xml file

### ISSUE THREAD

**Issue by decathorpe** [hughsie/appstream-glib#154]
When trying to use `appstream-util validate-{relax,strict} screenshot-tool.appdata.xml` (on latest fedora 25 and rawhide) to validate the file in question, I get the following error message (verbatim, including the suspicious line break in the second `'\n  '`):

```
screenshot-tool.appdata.xml: failed to parse screenshot-tool.appdata.xml: Error on line 134 char 7: <release> already set '⁠' and tried to replace with '
  '
```

First of all, I don't understand the error message as the appdata file looks valid (and is valid XML, I already checked that using the w3c xml online validator tool). Other elementary applications set their release data in this way too, and I don't see anything obvious to cause this error. Additionally, ximion's `appstreamcli validate FILE` parses the file correctly and validates it fine (barring the complaint / error about the ID not being a reverse domain-name).

I uploaded the file in question to <https://decathorpe.fedorapeople.org/misc/screenshot-tool.appdata.xml>.

I have to note that I can't say whether this is caused by a subtle error in the appdata.xml file in question or a bug in `appstream-glib` - but since the file is valid xml and it is parsed fine by `appstreamcli`, I suspect the latter is the case.

The version of `libappstream-glib` this occurs with is `libappstream-glib-0.6.8-2.fc25.x86_64` (and the rawhide equivalent).

If you have further questions, I hope I can help with debugging this issue.

**Comment by ximion** [comment]
Open the file with vi, and you see there are a few non-printable characters in the XML file. libxml2 which libappstream and appstreamcli use doesn't have a problem with these, but GMarkup, which appstream-glib uses apparently hates these characters.

The error message is weird though. (I don't know what the XML spec says about non-space/tab characters inbetween XML tags, but since libxml2 doesn't complain, I would guess it's generally okay, though arguably ugly).

**Comment by decathorpe** [comment]
Good catch! I would've never found that ...
So, I guess I should bug upstream about the weird characters in the file?

**Comment by decathorpe** [comment]
Removing the spurious unicode characters fixes validation, so I guess I can close this issue. Thanks for your help!

**Comment by ximion** [comment]
@hughsie Do you see any chance of appstream-glib handling these characters more gracefully? I looked at making libxml2 more strict for this case, but couldn't find any option for that.

**Comment by smcv** [comment]
> libxml2 which libappstream and appstreamcli use doesn't have a problem with these, but GMarkup, which appstream-glib uses apparently hates these characters.

The difference is that libxml2 is a real XML parser, whereas GMarkup is a parser for a commonly-used subset of XML.

If you want to restrict AppStream to that subset (I don't know whether it has a formal definition), which is probably a good idea tbh, then you'd have to check all character data (including [insignificant whitespace](http://xml.silmaril.ie/whitespace.html)) for weird whitespace characters like the ZWS.

**Comment by ximion** [comment]
> If you want to restrict AppStream to that subset

Nah, I'd rather not want to do that. At time, we say metainfo files are XML, I do not really want to attach a definition what "XML" actually means and what subset we allow. Also, there might be a time in the future where it makes sense to allow advanced XML features in it (I don't see that at time, but who knows?).

Having the format validation not differ between Richard's and my library would be nice though...

**Comment by fhoech** [comment]
> Edit: Those are unicode "zero-width spaces". No idea how they got in there.

Probably from the example AppData XML from https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html as just copy-and pasting that code and using it as a template will lead to exactly the same issue.

appstream-glib seems to have similar problems with carriage returns, in my opinion at least the latter should be treated as whitespace.
