### ISSUE TITLE
validate metadata_license doesn't like GPL

### ISSUE THREAD

**Issue by jbicha** [hughsie/appstream-glib#158]
Ubuntu 17.04 Beta
appstream-glib 0.6.9-1
aisleriot 1:3.22.1-1

`appstream-util validate /usr/share/appinfo/sol.appdata.xml `

```
sol.appdata.xml: FAILED:
• tag-invalid           : <metadata_license> is not valid [GPL-3.0+]
```

It's the same license as project_license so it should be valid.

**Comment by hughsie** [comment]
GPL isn't a metadata license, it's a code licence. See https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html

**Comment by ximion** [comment]
Hughsie was faster, but for completeness: See https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-metadata_license as well for additional information.

**Comment by jbicha** [comment]
The documentation says "Permissible license codes **include:** "

I read that to mean that any SPDX license was valid but those are some examples.

**Comment by ximion** [comment]
It doesn't say "permissible", it says *permissive* - and the GPL isn't a permissive license ;-)

**Comment by jbicha** [comment]
Wow, I thought I copy-pasted that. Anyway, my concern was about **include** which I understood to mean that the list isn't comprehensive.

So I recommend that the documentation be updated. I think I'm not alone in not immediately associating _permissive_ with "not GPL".

**Comment by ximion** [comment]
@jbicha What different term would you suggest? Any license which issoftware license and isn't "viral" as the GPL is fine here.

Btw, for your specific case I would suggest using the `FSFAP` license - it's tiny, mixes well with the GPL and is easy to add to d/copyright (while CC-0 technically enforces that you include it's very long license text with the sources).

(but the validators have a fixed whilelist at the moment: https://github.com/ximion/appstream/blob/master/src/as-spdx.c#L430 for appstreamcli and https://github.com/hughsie/appstream-glib/blob/master/libappstream-glib/as-app-validate.c#L999 for appstream-util)

**Comment by jbicha** [comment]
Nowhere does the documentation explicitly say that only permissive licenses are valid. What do you think about also explicitly saying that the GPL and LGPL are not permissive licenses? (because those licenses are very common among projects that will want to use appstream metadata)

I was going to propose that aisleriot just use GFDL-1.1 since it's on the whitelist and aisleriot's help already uses the license so it's easy.

**Comment by ximion** [comment]
The paragraphs should be more clear now, thanks!
