### ISSUE TITLE
validation fails when "optional" update_contact tag is missing

### ISSUE THREAD

**Issue by jbicha** [hughsie/appstream-glib#159]
Ubuntu 17.04 Beta
appstream-glib 0.6.9-1
aisleriot 1:3.22.1-1

```
$ appstream-util validate sol.appdata.xml 
sol.appdata.xml: FAILED:
• tag-missing           : <update_contact> is not present
Validation of files failed
```
But the [specification](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-update_contact) says that `update_contact` is optional.

By the way, the Aisleriot [developer](https://bugzilla.gnome.org/779434) wants to use a bugzilla URL as his update_contact. That seems a legitimate request and appstream-util doesn't complain about it, but the specification implies that it ought to be an email address.

**Comment by hughsie** [comment]
Maybe just use validate-relax instead? I'm quite keen on having an update contact as an email address as this is how my bulk-email-sending script works when we add to the spec and ask maintainers for more info to be added (not more than twice a year). I guess we should check it's an email at some point.
