### ISSUE TITLE
Validate kudos

### ISSUE THREAD

**Issue by matthiasclasen** [hughsie/appstream-glib#162]
I found polari had a <kudo>HighContast</kudo> in its appdata. I guess it didn't get much credit for that...
Given that we need to use free-form strings here, it would be good to
1) document the strings that are recognized by gnome-software
2) validate that we recognize the string

**Comment by hughsie** [comment]
appstream-util validate-relax --nonet /usr/share/app-info/xmls/fedora.xml.gz | grep kudo
    • attribute-invalid     : org.gnome.Polari.desktop: <kudo> is invalid [HighContast]

**Comment by hughsie** [comment]
I'm still talking with the other appstream maintainer about adding these to the spec.
