### ISSUE TITLE
meson: build fails without RPM installed in non-RPM system

### ISSUE THREAD

**Issue by rffontenelle** [hughsie/appstream-glib#169]
When building appstream-glib with JHBuild in my Arch Linux system, "enable-rpm" flag is set to 'true' by default, resulting in failure to build as Arch Linux doesn't have RPM (which you probably know already). A workaround is to add the flag `--Denable-rpm=false`, but it would be nice if meson enabled it based on the system, i.e. not enable for Arch.

**Comment by hughsie** [comment]
I thought "magic" dependencies were bad?

**Comment by rffontenelle** [comment]
Sorry, I didn't understand...

**Comment by rffontenelle** [comment]
For what is worth, JHBuild now disables RPM since [commit ff4f9785](https://git.gnome.org/browse/jhbuild/commit/?id=ff4f9785df94cd7c5daad18bbe132b5eb7a8e391).

**Comment by Conan-Kudo** [comment]
@rffontenelle What he means by "magic" dependencies are "auto-detecting and selecting features to enable based on what the system has".
