### ISSUE TITLE
appstrem-glib-0.7.0

### ISSUE THREAD

**Issue by bdubbs** [hughsie/appstream-glib#174]
This is more of a question than an issue.  Is appstrem-glib-0.7.0 a development release or a stable release?  I can find no reference to 0.7.0 on the wiki or home page.

In addition, it appears to now require rust and meson, but there is no mention of it in the NEWS or other files in the tarball.

**Comment by hughsie** [comment]
Good question - it's the new unstable, but if it helps I'm putting it in Fedora 26 as it's not going to break API or ABI. 0.6.x is the new super-stable-no-new-api branch. Meson is indeed a dep, although we do not depend on rust in any way.
