### ISSUE TITLE
Does not parse YAML CompulsoryForDesktops field

### ISSUE THREAD

**Issue by ximion** [hughsie/appstream-glib#175]
See https://appstream.debian.org/sid/main/metainfo/gnome-calculator.html for an example of this field in use and https://bugs.launchpad.net/ubuntu/+source/gnome-software/+bug/1698961 for the corresponding downstream bug report.

**Comment by AsciiWolf** [comment]
This is quite a serious issue as it allows users to remove many core GNOME applications using GNOME Software. Even GNOME Software itself can be removed.

**Comment by hughsie** [comment]
@AsciiWolf do you want to propose a patch? It should be a simple addition to https://github.com/hughsie/appstream-glib/blob/master/libappstream-glib/as-app.c#L5379

**Comment by AsciiWolf** [comment]
@hughsie No, I am not that good in C. Maybe @ximion could do it?

**Comment by ximion** [comment]
Thanks for fixing this, @iainlane :-) I was so occupied with things, that I didn't manage to fix this one myself.

**Comment by AsciiWolf** [comment]
It's broken again in Ubuntu 17.10 after updating appstream-glib to 0.7.1-1.

**Comment by iainlane** [comment]
On Thu, Aug 17, 2017 at 05:38:22PM +0000, AsciiWolf wrote:
> It's broken again in Ubuntu 17.10 after updating appstream-glib to 0.7.1-1.

No it's not. You're probably seeing a different bug
(https://bugzilla.gnome.org/show_bug.cgi?id=784748)

-- 
Iain Lane                                  [ iain@orangesquash.org.uk ]
Debian Developer                                   [ laney@debian.org ]
Ubuntu Developer                                   [ laney@ubuntu.com ]
