### ISSUE TITLE
Allow tagging screenshots by desktop environment

### ISSUE THREAD

**Issue by mcatanzaro** [hughsie/appstream-glib#18]
It might be nice to have a way to tag screenshots for a particular desktop environment. For example, I might take screenshots of an application in both GNOME and KDE and want to display the GNOME screenshots to GNOME users and the KDE screenshots to KDE users.

Or maybe this would not be nice, since it implies much more work creating the screenshots, and there's unlikely to be much consistency in which desktops the screenshots are taken for.

**Comment by hughsie** [comment]
@ximion Any comments?

**Comment by ximion** [comment]
I have a few concerns:
 * With translated and environment-specific screenshots, we pretty much explode the amount of screenshots upstream projects can maintain.
 * With many different environments, some might get outdated screenshots unless the upstream project is very committed to maintaining them and updating them with each new version.
 * What screenshot do we show if we have no matching environment?
 * This change impacts software centers which don't know this feature yet (they will show all screenshots until they have implemented support for this feature)

I don't see any fundamental issue with adding it, I just doubt that upstreams will deal with the bigger screenshot matrix as we expect them to do.

**Comment by hughsie** [comment]
I think translated screenshots are more valuable than per-desktop screenshots to end users, although i'll add just getting *any* screenshots out of some upstreams is hard.

**Comment by ximion** [comment]
Agreed. The amount of stuff having screenshots in Debian is pretty low.
I wouldn't mind adding an environment property to screenshots though, but only if this won't become another dead piece in the spec (and additional work for people using the AppStream lib) - I would like to have more than one person to use this (and that is, not saying "oh, sounds like a good idea", but saying "this is worth it and we will commit to making it happen for our software").

**Comment by hughsie** [comment]
I don't think this is useful, sorry.
