### ISSUE TITLE
Use Travis CI for build testing

### ISSUE THREAD

**Issue by williamcroberts** [hughsie/appstream-glib#181]
One should add a build/test steps for the free travis CI: https://travis-ci.org/ and add the build badge to your README.

**Comment by williamcroberts** [comment]
Are there tests for this?

**Comment by ignatenkobrain** [comment]
so file pull request, no?

**Comment by williamcroberts** [comment]
@ignatenkobrain You want me to create your Travis Account for you? This is something the project maintainer would need to do.

**Comment by ignatenkobrain** [comment]
no,  want you to send .travis.yml ;)

**Comment by ignatenkobrain** [comment]
hmm, looks like it is already there.

**Comment by ignatenkobrain** [comment]
And actually it even works (https://github.com/hughsie/appstream-glib/pull/176). So closing.

**Comment by williamcroberts** [comment]
@ignatenkobrain, you closed it without actually updating the README with a link to the travis ci. I have searched the public travis and see nothing. It's about providing testing and CI proof to consumers of the repo.

**Comment by pohly** [comment]
@williamcroberts please see also https://github.com/hughsie/appstream-glib/pull/182#issuecomment-318037197. I think we can trust @hughsie that he is really doing the checks that he mentions there, so I am not sure whether we need further proofs (which might be hard to provide in public).

@hughsie if you do the checks in public (for example, on https://travis-ci.org/ or on the public Coverity scan service), then I suppose adding links would be useful.

**Comment by williamcroberts** [comment]
If there is a test suite already there, then what can't be done in the public with respect to running it on the public travis? Coverity would definitely be nice. It's about test evidence, not about trust. I'm sure @hughsie is a great person, but proof is always nice.

**Comment by hughsie** [comment]
> Coverity would definitely be nice

Well, this is the link, but I think you need a Coverity account to look at it, and you need permission to actually look at the scan results... https://scan.coverity.com/projects/hughsie-appstream-glib?tab=overview -- clang is done locally, I guess I could do this on travis too in the future.

> I'm sure @hughsie is a great person

Sure, I think so! :)

**Comment by pohly** [comment]
On Wed, 2017-07-26 at 19:40 +0000, William Roberts wrote:
> Coverity would definitely be nice. It's about test evidence, not
> about trust.

Let's just say I know about a certain company which uses a certain
static code analysis tool and cannot talk about that in public.
Consumers of the open source projects published by that company have to
have trust in the company, because there are is no public test
evidence.
It's of course better if there is such evidence, but sometimes one has
to go with trust instead.
> 
>   
>   
> 
> 
> 
> 
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
> 5493e4bb","name":"GitHub"},"entity":{"external_key":"github/hughsie/a
> ppstream-glib","title":"hughsie/appstream-glib","subtitle":"GitHub
> repository","main_image_url":"https://cloud.githubusercontent.com/ass
> ets/143418/17495839/a5054eac-5d88-11e6-95fc-
> 7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
> .com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
> b52498112777.png","action":{"name":"Open in
> GitHub","url":"https://github.com/hughsie/appstream-
> glib"}},"updates":{"snippets":[{"icon":"PERSON","message":"@williamcr
> oberts in #181: If there is a test suite already there, then what
> can't be done in the public with respect to running it on the public
> travis? Coverity would definitely be nice. It's about test evidence,
> not about trust. I'm sure @hughsie is a great person, but proof is
> always nice."}],"action":{"name":"View
> Issue","url":"https://github.com/hughsie/appstream-
> glib/issues/181#issuecomment-318160105"}}}

**Comment by williamcroberts** [comment]
@pohly That is the most ridiculous answer I have heard when there is two free, publicly usable services for CI and Static Analysis that could be deployed public facing.
