### ISSUE TITLE
appstream-util can no longer detect duplicated screenshots?

### ISSUE THREAD

**Issue by TC01** [hughsie/appstream-glib#185]
I was recently building a package on both Fedora (technically RPM Fusion, but that shouldn't be relevant to this issue) and EPEL 7 that I'd written an appstream file for. I took two similarly named screenshots:

* https://www.acm.jhu.edu/~bjr/fedora/rpmfusion/tilem/tilem_83plus.png
* https://www.acm.jhu.edu/~bjr/fedora/rpmfusion/tilem/tilem_84plus.png

When I went to actually write the appdata file however, I made a minor typo, listing the same screenshot twice:

```
        <screenshot type="default">
            <image>https://www.acm.jhu.edu/~bjr/fedora/rpmfusion/tilem/tilem_84plus.png</image>
        </screenshot>
        <screenshot>
            <image>https://www.acm.jhu.edu/~bjr/fedora/rpmfusion/tilem/tilem_84plus.png</image>
        </screenshot>
```

My spec invokes appstream-util validate-relax as follows, as specified by the [AppData Guidelines](https://fedoraproject.org/wiki/Packaging:AppData)

```
appstream-util validate-relax --nonet %{buildroot}/%{_datadir}/appdata/*.appdata.xml
```

However this did not find any issues, so I didn't notice the problem... until I built on EPEL 7. Then I got back the following error message:

```
FAILED:
? duplicate-data        : <screenshot> has duplicated data
Validation of files failed
```

I was momentarily confused, since this hadn't failed on Fedora, but when I went and checked the appdata file I discovered the issue. It looks like somewhere between libappstream-glib 0.3.6 (current version in EPEL 7) and libappstream-glib 0.6.13 (current version in F25, where the build also passed), this check stopped happening? It seems like a useful check against packagers who make silly typos in their appdata files (like me). Was this turned off intentionally? Or is it a bug?

**Comment by hughsie** [comment]
We do still call `as_app_validate_image_url_already_exists` but I think the builder just automatically de-duplicated your screenshots. Sure enough, `as_app_parse_file` sets AS_APP_TRUST_FLAG_CHECK_DUPLICATES which we use to load the AppData prior to validation. I'll add this to the existing problem bitfields now.
