### ISSUE TITLE
[Fedora 25] appstream-builder: how to add an desktop Application without appdata?

### ISSUE THREAD

**Issue by CrazyCxl** [hughsie/appstream-glib#193]
Is there any way to add an desktop Application? when the rpm's  content like:
```
/usr/bin/xxx
/usr/share/applications/xxx.desktop
/usr/share/icons/hicolor/24x24/apps/xxx.png
/usr/share/icons/hicolor/64x64/apps/xxx.png
```

I tried to add `asb_plugin_check_filename` in asb-plugin-desktop.c , but it was  warned "Asb-DEBUG: WARNING: Failed to run process 'desktop': no asb_plugin_process".

**Comment by ximion** [comment]
It looks like the icon size here is too small - you will need a bigger icon (64x64) in any case.

**Comment by CrazyCxl** [comment]
@ximion Thanks for your reply,But after adding a bigger icon(/usr/share/icons/hicolor/64x64/apps/xxx.png), it still doesn't work.

**Comment by ximion** [comment]
Yeah, that warning message looks fishy to me, but I do not know as-builder enough to know what triggers it. This ultimately is something for @hughsie to answer, when he is back in software-engineering action.
However, AFAIK asb does not handle any .desktop files that do not ship a metainfo file, so you will have to add one in any case if you want this to work.

**Comment by CrazyCxl** [comment]
@ximion OK, Thanks for your suggest.
