### ISSUE TITLE
as-self-test fails on 32-bit

### ISSUE THREAD

**Issue by andreasbaumann** [hughsie/appstream-glib#196]
```
--- stderr ---
**
As:ERROR:../appstream-glib/libappstream-glib/as-self-test.c:3909:as_test_store_versions_func: assertion failed (error == NULL): --- /tmp/b      2017-10-22 09:41:24.388296490 +0200
+++ /tmp/a      2017-10-22 09:41:24.388296490 +0200
@@ -6,9 +6,7 @@
 <arch>i386</arch>
 </architectures>
 <releases>
-<release timestamp="123" version="0.1.2">
-<description><p>Hello</p></description>
-</release>
+<release timestamp="123" version="0.1.2"/>
 </releases>
 </component>
 </components>
 (-g-type-private--GTypeFlags, 0)
```

**Comment by andreasbaumann** [comment]
[build_archlinux32.txt](https://github.com/hughsie/appstream-glib/files/1404707/build_archlinux32.txt)

**Comment by ximion** [comment]
This is fixed with https://github.com/hughsie/appstream-glib/commit/f5fb6e40f5aeba2cde1de0406815af876d41be3a already :-)

**Comment by andreasbaumann** [comment]
I dought it's that fix (or that fix alone).

But I can confirm that the newest git revision e791b7ef5f9760b7bad24978c7d88d5bc79d6bd3 builds and the tests run without producing any errors.

**Comment by hughsie** [comment]
This is the fix: https://github.com/hughsie/appstream-glib/commit/a1481d201d089f9e70a0cf48a0424315e0f6cdaf -- but thanks for testing master. I'll do a new tarball in a few days time.

**Comment by ximion** [comment]
Urgh, yeah, I miscopied that URL ;-)
A new tarball would be neat, there are quite some changes in master that would be nice to have.
