### ISSUE TITLE
Update list of depencies & build instructions

### ISSUE THREAD

**Issue by suve** [hughsie/appstream-glib#201]
The list of depencies is outdated. On my system, I was missing the following:
```
gcab gperf json-glibc-devel libgcab-devel libstemmer-devel libuuid-devel meson
```
Out of these, `libgcab` being missing was not detected during `./configure`.

The build instructions are also outdated.

**Comment by hughsie** [comment]
Could you do a PR for me against README.md please? I'd appreciate it very much.
