### ISSUE TITLE
size optimize extracted icons with pngquant

### ISSUE THREAD

**Issue by lapo** [hughsie/appstream-glib#203]
I'm playing with lossy png optimization, using pngquant (see pngquant.org), on adwaita icon theme icons and noticed huge savings with a very little loss in quality on 256x256 and 512x512 icons, so I tried this on fedora appstream icons, here's the results:

[lapo@localhost icons]$ ls
fedora  rpmfusion-free-26  rpmfusion-nonfree-26
[lapo@localhost icons]$ du -s
17380	.
[lapo@localhost icons]$ time find -name '*.png' -exec pngquant --skip-if-larger --strip --ext .png -f --speed 1 {} \;

real	0m29,370s
user	1m11,401s
sys	0m3,377s
[lapo@localhost icons]$ du -s
10488	.

I think it worths considering using this tool to save some space, so maybe we can fit more icon sizes in, needed by the elementary devs and latest Allan designs.

**Comment by DimStar77** [comment]
Why using the cli tool and not via the library?

https://github.com/ImageOptim/libimagequant

**Comment by hughsie** [comment]
Isn't libimagequant GPLv3+?

**Comment by DimStar77** [comment]
fair point - so is pngquant, but since you don't link, it doesn't matter; Might be worthy to contact upstream though to validate if they really meant to give the lib as GPL instead of LGPL (but even if they switch, I'd assume them to go LGPL-3.0, which would pull up as-glib too)

**Comment by hughsie** [comment]
Could you open an issue against their project please, I'm running around like a crazy man today. Thanks :)

**Comment by DimStar77** [comment]
of course - https://github.com/ImageOptim/libimagequant/issues/11
