### ISSUE TITLE
Bad icon and screenshot for Android Emoji font

### ISSUE THREAD

**Issue by mavit** [hughsie/appstream-glib#207]
The icon and screenshot for the Android Emoji font in Gnome Software are boxes rather than characters from the font.

I notice that if I comment out the following lines in `asb_font_add_languages()`, and, additionally, I specify `<languages><lang>und-zsye</lang></languages>` in the `metainfo.xml` accompanying the font, we end up with a screenshot containing only occasional boxes (which seems reasonable, given that this is an older font that doesn't cover the latest emoji):

```
	/* assume 'en' is available */
	if (!any_added)
		as_app_add_language (AS_APP (app), 0, "en");
```

It seems that it may be better, then, to prefer the `metainfo.xml`-specified language to `en` if none is detected.

**Comment by hughsie** [comment]
I guess that makes sense.
