### ISSUE TITLE
appstream-compose breaks screenshot order and default selection in appdata

### ISSUE THREAD

**Issue by kparal** [hughsie/appstream-glib#210]
This has been originally reported as https://github.com/flatpak/flatpak-builder/issues/76 .

I noticed that screenshots that I defined in appdata are displayed completely wrong for my app:
https://github.com/flathub/org.freefilesync.FreeFileSync

In the source `data/org.freefilesync.FreeFileSync.appdata.xml` file, there's this:
```
  <screenshots>
    <screenshot type="default">
      <caption>Manual synchronization of two folders</caption>
      <image>https://www.freefilesync.org/images/screenshots/openSUSE.png</image>
    </screenshot>
    <screenshot>
      <caption>Online storage support</caption>
      <image>https://www.freefilesync.org/images/screenshots/sftp.png</image>
    </screenshot>
    <screenshot>
      <caption>Synchronization settings</caption>
      <image>https://www.freefilesync.org/images/screenshots/sync-settings.png</image>
    </screenshot>
    <screenshot>
      <caption>Automatic synchronization</caption>
      <image>https://www.freefilesync.org/images/screenshots/RealTimeSync.png</image>
    </screenshot>
  </screenshots>
```

However, after building the app, in `builddir/files/share/app-info/xmls/org.freefilesync.FreeFileSync.xml.gz` there's this:
```
    <screenshots>
      <screenshot type="default">
        <caption>Automatic synchronization</caption>
        <image type="source">https://www.freefilesync.org/images/screenshots/RealTimeSync.png</image>
      </screenshot>
      <screenshot>
        <caption>Manual synchronization of two folders</caption>
        <image type="source">https://www.freefilesync.org/images/screenshots/openSUSE.png</image>
      </screenshot>
      <screenshot>
        <caption>Online storage support</caption>
        <image type="source">https://www.freefilesync.org/images/screenshots/sftp.png</image>
      </screenshot>
      <screenshot>
        <caption>Synchronization settings</caption>
        <image type="source">https://www.freefilesync.org/images/screenshots/sync-settings.png</image>
      </screenshot>
    </screenshots>
```

Notice that the order or screenshots have been changed (shifted by one), and the default screenshot has been changed as well (it stayed as the first item, but the value got shifted, so it's a different image).

It seems appstream-compose mangles the screenshots section.

**Comment by hughsie** [comment]
Changing the default is indeed a bug. The order isn't prescribed, it's XML afterall. You can however control the priority that they are shown. Simply use `priority="number"` for each `<screenshot>` and it will respect that. I'll fix the default bug now.

**Comment by kparal** [comment]
> Simply use priority="number" for each <screenshot> and it will respect that.

That's not in docs, I created https://github.com/hughsie/appstream-glib/issues/213 for that.
