### ISSUE TITLE
as-glib does not now what to do with pngquant's exit code 98

### ISSUE THREAD

**Issue by DimStar77** [hughsie/appstream-glib#223]
as-glib starts pngquant with --skip-if-larger, which in turn makes pngquant exit with $retval=98 if the image was thus not resized.

as-builder though takes this as a 'failure of pngquant' and aborts the generation of appdata.xml.gz, which is hopefuffly not what was intented to happen.

I have an RPM/Testcase to reproduce this.

**Comment by hughsie** [comment]
Is there a "do nothing and return 0 if larger" option?

**Comment by DimStar77** [comment]
Not according the man page
