### ISSUE TITLE
Please update SPDX licenses

### ISSUE THREAD

**Issue by jbicha** [hughsie/appstream-glib#225]
[libappstream-glib/as-license-ids.txt](https://github.com/hughsie/appstream-glib/blob/master/libappstream-glib/as-license-ids.txt) says it is up to date as of version 2.6.

Please update to version 3.0 (released in late December 2017).

This is requested for gnome-terminal and aisleriot where the developer is trying to use `GFDL-1.3-only` which is valid for SPDX but not for AppStream yet. Actually, I guess that new syntax will be a bit of a pain since the old `GPL-3` and `GPL-3+` syntax is used in a lot of places.

**Comment by hughsie** [comment]
The new syntax is a pain; it'll break a lot of things. I've got a local patch that just syncs the list with 3.0, but it's going to need some code changes to avoid breaking the world.
