### ISSUE TITLE
Scale icons instead of padding

### ISSUE THREAD

**Issue by kalev** [hughsie/appstream-glib#227]
We had a long discussion in #packagekit the other day what to do with 48x48 px icons that a lot of apps ship and appstream mandating 64x64 px. I believe the pragmatic conclusion was to keep the bar at 48x48 px for apps to get included in appstream metadata, as we'd otherwise lose too many in Fedora.

If we do that, then there's two ways how to turn a 48x48 px icon into a 64x64 px one on the generator side: scale up, or pad. Right now we are padding.

This is a tradeoff decision, where I believe the trade off is as follows:

a) pad icons in the generator: icons look good (sharp), gnome-software looks bad (icons not properly aligned to UI layout)
b) scale icons in the generator: icons look bad (blurry), gnome-software looks good (icons are properly aligned in the UI layout)

Let's switch to doing (b), as I think we _want_ to make low-res icon apps looks a bit bad to get them to ship better icons, and we also want to make gnome-software UI layout look good, even when it's showing apps with bad icons.

**Comment by hughsie** [comment]
@kalev didn't you have a PR for this somewhere?

**Comment by kalev** [comment]
I think it's already fixed in appstream-glib, can't remember which commit exactly fixed it.
