### ISSUE TITLE
a bug in asb_package_guess_from_filename 

### ISSUE THREAD

**Issue by CrazyCxl** [hughsie/appstream-glib#228]
in appstream-glib/libappstream-builder/asb-package.c asb_package_guess_from_filename
---
if priv->filename likes `/xxx/xxx-xxx/xxx-xxx/free/x86_64/xxx.x86_64.rpm` , then priv will get 

```
arch:x86_64
release:ccc/free/x86_64/test
version:bbb/ccc
name:bbb
```

Obviously, that's wrong.

**Comment by hughsie** [comment]
I guess that's correct, but how are you launching the builder to get that?

**Comment by CrazyCxl** [comment]
There some  rpms have inaccuracy  filename  likes [atom.x86_64.rpm](https://atom-installer.github.com/v1.24.0/atom.x86_64.rpm?s=1518059210&ext=.rpm) . because of the same wrong package name ,the builder set the package enabled to false in `asb_context_disable_older_pkgs`
