### ISSUE TITLE
appstream-util validate fails with example file from docs

### ISSUE THREAD

**Issue by fhoech** [hughsie/appstream-glib#230]
Validation of the example AppData file from https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html fails because it doesn't find a root element (appstream-util 0.7.7 from f27):

```
$ appstream-util validate org.gnome.gnome-power-statistics.xml
org.gnome.gnome-power-statistics.xml: No valid root node specified
```

[org.gnome.gnome-power-statistics.xml.gz](https://github.com/hughsie/appstream-glib/files/1868325/org.gnome.gnome-power-statistics.xml.gz)

**Comment by fhoech** [comment]
Alright, the error was not due to the XML contents themselves, but due to me omitting the .appdata suffix from the filename before the .xml extension (still, maybe the error message could be improved for that case?). Adding the .appdata suffix, the validation still fails though for both `validate` and `validate-relax`, although the latter only fails because the screenshots don't exist (anymore?) online:

```
$ appstream-util validate org.gnome.gnome-power-statistics.appdata.xml 
org.gnome.gnome-power-statistics.appdata.xml: FAILED:
• tag-missing           : <translation> not specified
• tag-missing           : <update_contact> is not present
• url-not-found         : <screenshot> failed to download (HTTP 404: Not Found) [http://www.hughsie.com/en_US/main.png]
• url-not-found         : <screenshot> failed to download (HTTP 404: Not Found) [http://www.hughsie.com/en_US/preferences.png]
• style-invalid         : <p> does not end in '.|:|!' [Fixes issues X, Y and Z]
• style-invalid         : <p> is too short [Fixes issues X, Y and Z]
• style-invalid         : Content before <ul> is too short [182], at least 300 characters required
• style-invalid         : <li> is too short [First item] minimum is 20 chars
• style-invalid         : <li> is too short [Second item] minimum is 20 chars
Validation of files failed
```

```
$ appstream-util validate-relax org.gnome.gnome-power-statistics.appdata.xml 
org.gnome.gnome-power-statistics.appdata.xml: FAILED:
• url-not-found         : <screenshot> failed to download (HTTP 404: Not Found) [http://www.hughsie.com/en_US/main.png]
• url-not-found         : <screenshot> failed to download (HTTP 404: Not Found) [http://www.hughsie.com/en_US/preferences.png]
Validation of files failed
```

**Comment by ximion** [comment]
`appstream-utils` is just *really* strict. The **translation` and `update_contact` tags are completely optional, the style issues are no formal validation of the AppStream specification (it's more a "best practices" thing).
The only real issue is the missing screenshots, and that should likely be fixed to have a better example.
If you want to, please [report an issue against AppStream](https://github.com/ximion/appstream/issues) about that. As for appstream-glib's validator strictness, I do think that is very intentional ;-)
