### ISSUE TITLE
appstream-util doesn't compare versions correctly

### ISSUE THREAD

**Issue by bochecha** [hughsie/appstream-glib#231]
I'm using the following appdata file: https://github.com/flathub/org.blender.Blender/blob/5bbc2535bfaee1f29d5f8ae6eb0a6cc82a9e9b70/org.blender.Blender.appdata.xml

It includes a few releases:

```xml
    <releases>
        <release version="2.79b" date="2018-03-23">
            <description>
                <p>This is a maintenance release fixing many bugs.</p>
            </description>
        </release>
        <release version="2.79a" date="2018-02-27">
            <description>
                <p>This is a maintenance release fixing over 200 bugs.</p>
            </description>
        </release>
        <release version="2.79" date="2017-09-12">
            <description>
                <p>New features:</p>
                <ul>
                    <li>Denoiser</li>
                    <li>Filmic color management</li>
                    <li>PBR shader</li>
                    <li>Shadow catcher</li>
                    <li>Surface Deform modifier</li>
                    <li>More bundled add-ons</li>
                    <li>...And many more!</li>
                </ul>
                <p>Enhancements:</p>
                <ul>
                    <li>Faster OpenCL</li>
                    <li>Cycles improvements</li>
                    <li>Modeling tool improvements</li>
                    <li>Animation improvements</li>
                    <li>Grease Pencil improvements</li>
                    <li>Automatic scaling on high DPI displays</li>
                    <li>Alembic import and export improvements</li>
                    <li>...And many more!</li>
                </ul>
            </description>
        </release>
    </releases>
```

Validation fails:

```
$ appstream-util validate-relax org.blender.Blender.appdata.xml 
org.blender.Blender.appdata.xml: FAILED:
• tag-invalid           : <release> versions are not in order [2.79a before 2.79]
Validation of files failed
```

However they are in order, as 2.79a is a bugfix release that came after 2.79, and 2.79b is a bugfix release that came after 2.79a.

A less creative upstream would have called them 2.79.1 and 2.79.2, but Blender upstream calls them 2.79a and 2.79b. (We're trying to get them to accept the appdata file upstream. They've been using this scheme forever, and probably won't be interested in changing their practice just to please the appstream validator)

As a further point of reference, rpm agrees with upstream Blender:

```
$ rpmdev-vercmp 2.79 2.79a
2.79 < 2.79a
```

This is particularly bad as it fails Flathub builds. (I'll just use a workaround for now)

**Comment by Conan-Kudo** [comment]
I've previously documented [how RPM's version comparison works](https://fedoraproject.org/wiki/PackagingDrafts/TildeVersioning).

Debian's version sorting logic is documented in [`deb-version(5)`](https://www.mankier.com/5/deb-version).

AppStream / AppStream-GLib should handle this correctly.

**Comment by ximion** [comment]
FWIW, AppStream handles this case correctly (which is no surprise, since it uses version comparison code like RPM): https://github.com/ximion/appstream/blob/master/src/as-utils.c#L996
I want to extend that algorithm though to also handled cases of Debian version numbers correctly, so we have some compromise-version-comparison that works best for most or all version numbers used in the RPM and Deb world (AppStream's current code should work for everything upstream can come up with though ^^).

**Comment by ximion** [comment]
FWIW, AppStream handles this case correctly (which is no surprise, since it uses version comparison code adapted from RPM): https://github.com/ximion/appstream/blob/master/src/as-utils.c#L996
I want to extend that algorithm though to also handled cases of Debian version numbers correctly, so we have some compromise-version-comparison that works best for most or all version numbers used in the RPM and Deb world (AppStream's current code should work for everything upstream can come up with though ^^).

**Comment by Conan-Kudo** [comment]
@ximion These days, I think the RPM and DPKG version comparison logic works more or less the same, though RPM's is slightly stricter...

**Comment by ximion** [comment]
@Conan-Kudo Not really... I have an implementation of the Debian version comparison algorithm in Laniakea (Debian archive management suite, D code) and reused the tests in AppStream. Some of the tests for specific versions fail with the RPM comparison code, and I planned to address that (and then forgot about it): https://github.com/ximion/appstream/blob/master/tests/test-basics.c#L400
Maybe it's time to fix it now ;-)
Fortunately though, the AppStream code compares mostly upstream versions, comparing distro versions is less likely.

**Comment by hughsie** [comment]
This is tricky. AppStream-glib has to support firmware versions like `blue123` i.e. *really* non-alpha-numeric versions. I suspect we can fix this by making the "switch to strcmp" mode only used when both versions are alpha, e.g. `blue123` and `blue124`

**Comment by ximion** [comment]
@hughsie Oh wow, this sounds like an absolute nightmare with lots of pain waiting in future! (there will definitely be conflicts between who considers what version number to be newer) Can't you just force people uploading to LVFS to use sane version numbers?

**Comment by hughsie** [comment]
@ximion the people doing the uploading, sure, the people doing the marketing (and who want the "same" version numbers as Windows) not so much. Saying that, it's only two firmwares so far.

**Comment by Conan-Kudo** [comment]
@ximion Since RPM 4.10, those special cases in dpkg are also in RPM. Version comparison strings should evaluate the same way now.

**Comment by ximion** [comment]
@hughsie For those cases you could maybe have LVFS mangle the version number to something sane with a custom rule, if the vendors really don't want to give in...

**Comment by hughsie** [comment]
So the LVFS kinda already has that, a so called "display version" -- maybe my complication isn't valid anymore.
