### ISSUE TITLE
appstream-util should warn when using deprecated spdx license

### ISSUE THREAD

**Issue by TingPing** [hughsie/appstream-glib#235]
A lot of projects still use `GPL-2.0` for example. Maybe something to enable just for `validate-strict`.

**Comment by hughsie** [comment]
The thing is, @ximion is right; SPDX have changed how the GPL licence identifier is specified twice already, and I don't have much hope it's static now. We already use a not-quite-SPDX license field to avoid having to re-contact ~2000 upstream projects and ask them to change to the spec-de-jour. Good idea, and thanks for filing the bug, and maybe we can revisit in a few years and do what you suggest.
