### ISSUE TITLE
Do not override the project group of items based on heuristics

### ISSUE THREAD

**Issue by joaquimrocha** [hughsie/appstream-glib#236]
I think that appstream-glib is incorrectly overriding the `project_group` of the `AsItem` by using the heuristics even when the `OnlyShowIn` is set up. I have noticed this in the `gnome-system-monitor-kde.desktop` file, where it's got `OnlyShowIn=KDE` set but it ends up with `GNOME` as the project_group instead. I noticed the [heuristics code](https://github.com/hughsie/appstream-glib/blob/master/libappstream-glib/as-app-desktop.c#L64) and removing the bugzilla related entries from the desktop file let the item get the `project_group` as `KDE` as expected.

I think we should only assign values from heuristics when the values are not yet set. But I may be missing some context so I am opening this issue now.

**Comment by hughsie** [comment]
I think we should only set the project group in the heuristics code if it's not already set.
