### ISSUE TITLE
Provide tool to add release info to appdata files

### ISSUE THREAD

**Issue by eszlari** [hughsie/appstream-glib#237]
With the tool `desktop-file-edit` from `desktop-file-utils` (https://www.freedesktop.org/wiki/Software/desktop-file-utils/) one can easily edit .desktop file, e.g.:

```
desktop-file-edit --set-key=Icon --set-value='org.example.App' /app/share/applications/org.example.App.desktop
```
This is used a lot at Flathub (https://flathub.org) to fix desktop files while packaging for flatpak.

It would be very handy, if appstream would provide something similar, for adding release informations to appdata files, e.g.:

```
appdata-file-edit --add-release=1.0.0,2018-03-15 /app/share/appdata/org.example.App.appdata.xml
```
This would help us at Flathub, since there are upstreams that either forget to update their appdata or don't want to. I, as a maintainer of several flatpaks at Flathub, have experienced both.

**Comment by hughsie** [comment]
Don't you also need to add multi-paragraph release notes as well?

**Comment by eszlari** [comment]
On Flathub at least one release entry is desired, so people can see what the currently available version is, when they are using their software store app or `$ flatpak search` on the command line. But this not a hard requirement, there still a lot of apps on Flathub that have no release info at all.

**Comment by hughsie** [comment]
I don't really want a command line option; I'd like upstream to provide multi-paragraph release notes. Sorry.
