### ISSUE TITLE
should user configure gcab and libsoup deps

### ISSUE THREAD

**Issue by henglinli** [hughsie/appstream-glib#238]
when build for flatpak, appstream-glib pull lots of deps
appstream-glib should be configureable for it's deps

**Comment by hughsie** [comment]
What dep is problematic? You can already disable the builder.

**Comment by henglinli** [comment]
libgcab and libarchive   
libsoup and libcurl 
can be chosen only one ?
the meson.build directly pull them both.

**Comment by hughsie** [comment]
We're discussing gcab in https://github.com/hughsie/appstream-glib/pull/240

**Comment by hughsie** [comment]
I don't also think we depend on libcurl, right?

**Comment by henglinli** [comment]
should be my mistake
