### ISSUE TITLE
Could we get a release soon?

### ISSUE THREAD

**Issue by Jehan** [hughsie/appstream-glib#239]
Hello!

I was wondering if it were possible to get a release soon, because bug #234 actually prevents me from releasing the GIMP flatpak anymore on flathub. I am assuming flathub would want to use a released version of appstream-glib, but no version with the fix has been released yet.

All my builds end up with this error:

```
Processing application org.gimp.GIMP
org.gimp.GIMP:                     AppData problem: tag-invalid : <release> versions are not in order [2.10.0 before 2.10.0~rc2]
Error loading AppData file: AppData file /app/share/appdata/org.gimp.GIMP.appdata.xml was not valid
Error: ERROR: appstream-compose failed: Child process exited with code 1
```

See for instance my last failing build: https://flathub.org/builds/#/builders/2/builds/1507

Thanks!

**Comment by hughsie** [comment]
I'd like to merge https://github.com/hughsie/appstream-glib/pull/240 and then I think we can.
