### ISSUE TITLE
appstream-util validate-relax & icons

### ISSUE THREAD

**Issue by jdeluyck** [hughsie/appstream-glib#243]
When packaging an app (notepadqq) for Fedora I came across the fact that appstream-util validate-relax doesn't accept the <Icon/> line inside a <component type=desktop> block.

According to the spec this should be allowed (as type=desktop is just a specialisation, and should accept everything from the generic block).

Is this a bug?

Example xml file that doesnt' work for me:
https://raw.githubusercontent.com/notepadqq/notepadqq/master/support_files/notepadqq.appdata.xml

Kind regards

**Comment by hughsie** [comment]
The icon is supposed to be "inherited" from the .desktop file. Why are you using a remote icon in the appdata file and a local icon in the desktop file?

**Comment by ximion** [comment]
An icon of type `stock` or `local` would technically be allowed in the file (overriding whatever is in the .desktop file), but remote icons aren't, especially not if their type specialization is missing like in this case.
I should probably clarify that in the spec and also make using a remote icon in metainfo files in general an error in `appstreamcli` (but for sure make it an error to use web URLs in a non-remote-type icon, if that isn't an error already).

**Comment by jdeluyck** [comment]
@hughsie Inherited, as in, it doesn't need to be put in, or it does need to be put in there?

With regard to the local vs remote Icon, I'll take this up with the author.

**Comment by bam80** [comment]
> The icon is supposed to be "inherited" from the .desktop file.

What if I don't have .desktop file yet? It supposed to be extracted later on flatpak install time, using "apply_extra" script.
Also, icons from .desktop file could need to be overridden (for example, I want different icons for AppData and .desktop).

**Comment by sergiomb2** [comment]
> The icon is supposed to be "inherited" from the .desktop file. Why are you using a remote icon in the appdata file and a local icon in the desktop file?

sorry on https://www.freedesktop.org/software/appstream/docs/chap-CollectionData.html#tag-ct-icon
in icon section document says that `<icon type="stock">` is valid when apparently is not.
it is the specification of appstream and imho or we change the specification or we need allow as valid   `<icon type="stock">` .
I don't understand well the situation , this appstream-glib is just an helper on appstream and we can ignore the result of appstream-util  validate-relax ?
