### ISSUE TITLE
'Meson' configuration

### ISSUE THREAD

**Issue by sylale** [hughsie/appstream-glib#248]
This library is used to compile Gimp 2.99 since July 2, 2018.
Would it be possible to have a 'meson' configuration that works with mingw32, mingw64 and msys2.

Thank you :o)

**Comment by hughsie** [comment]
I'm not sure what would be required to be honest.

**Comment by sylale** [comment]
Can you provide a 'makefile' that runs on Linux.
I could at least adapt it.
Thank you.
:o)

**Comment by hughsie** [comment]
> Can you provide a 'makefile' that runs on Linux.

Can you be more precise please; I'm really not sure what you're asking for.
