### ISSUE TITLE
build error - libgcap?

### ISSUE THREAD

**Issue by prlw1** [hughsie/appstream-glib#250]
I can't build appstream-glib because of an apparent lack of libgcap:

Native dependency uuid found: YES 2.31.0
Native dependency glib-2.0 found: YES 2.56.1
Native dependency gmodule-2.0 found: YES 2.56.1
Native dependency gio-unix-2.0 found: YES 2.56.1
Native dependency libarchive found: YES 3.3.2
Native dependency libsoup-2.4 found: YES 2.62.2
Native dependency json-glib-1.0 found: YES 1.2.8
Native dependency gdk-pixbuf-2.0 found: YES 2.36.12
Dependency libgcab-1.0 found: NO

$ git checkout appstream_glib_0_7_9
Note: checking out 'appstream_glib_0_7_9'.
...
$ git grep -i gcap
$

Thoughts?

**Comment by hughsie** [comment]
it's gca**b**

**Comment by prlw1** [comment]
I was about to write "I can't type" thanks - you are fast!
