### ISSUE TITLE
appstream-util: inconsistent argument order between HTML functions

### ISSUE THREAD

**Issue by suve** [hughsie/appstream-glib#253]
- `status-csv` and `status-html` expect the following arguments: `input.tar.gz output.{csv,html}`

- `matrix-html` expects the following arguments: `output.html input.tar.gz`

I think it'd be good to maintain some consistency regarding the ordering of arguments. 

Also, `matrix-html` can take multiple `input.tar.gz` arguments, while the `status-*` functions can only take one. Is there any particular reason behind this?

**Comment by hughsie** [comment]
I guess `output` then `input1` [`inputn`] globally makes sense. Would you be able to submit a PR for this fix please?

**Comment by suve** [comment]
Personally I was thinking about `input1 [input2...] output`, since that's the order `cp` and other coreutils use, but that's mostly a matter of preference.

I will submit a pull request in the following days.

**Comment by hughsie** [comment]
Yup, `input1 [input2...] output` would be fine too for me.
