### ISSUE TITLE
ld: unknown option: --version-script

### ISSUE THREAD

**Issue by yurikoles** [hughsie/appstream-glib#258]
This happens on macOS and probably on FreeBSD to, because this flag is supported only by GNU ld.

Related issue: https://github.com/mesonbuild/meson/issues/3923
Workaround for similar issue in gvfs: https://gitlab.gnome.org/GNOME/gvfs/merge_requests/5/

**Comment by hughsie** [comment]
I'd much rather meson just support a `version_script` argument when building the library; that way it can use it if supported, otherwise just ignore it.

**Comment by yurikoles** [comment]
The problem is that meson always passes `version_script`, please see related issue in OP.

**Comment by hughsie** [comment]
Right, I'd much rather fix meson rather than working around it.
