### ISSUE TITLE
appstream-builder creates files with invalid component type "shell-extension"

### ISSUE THREAD

**Issue by StefanBruens** [hughsie/appstream-glib#260]
shell-extension is no valid component type, the correct type for GNOME shell extensions would be "addon".

This breaks loading of metadata with e.g. appstreamcli, or any of the appstream bindings, e.g. AppstreamQt.

See https://github.com/ximion/appstream/issues/199 for more info.

**Comment by hughsie** [comment]
Libappstream needs to not fail if it encounters unknown types or tags.

**Comment by hughsie** [comment]
"be conservative in what you do, be liberal in what you accept from others." -- it's XML, the X stands for extensible. We can't lock the specification and make no changes, and neither can we go back in time and make different design decisions. Sorry, but I don't think there's much I can do. Long term we can migrate to the addon thing, but that's going to need the clients being changed as well.

**Comment by ximion** [comment]
> Libappstream needs to not fail if it encounters unknown types or tags.

It doesn't fail, it just warns about it.

**Comment by ximion** [comment]
> Libappstream needs to not fail if it encounters unknown types or tags.

It doesn't fail, it just warns about it. Libappstream will never ignore components and not give the user/developer any hint on why it was dropped or that something was ignored.
While the AppStream spec will evolve, appstream-glib clearly generates invalid data here that has never been described in any specification. Hence, it technically can't even be called AppStream.

**Comment by ximion** [comment]
> "be conservative in what you do, be liberal in what you accept from others." 

By that logic, appstream-builder should stop to produce wrong component types.

> it's XML, the X stands for extensible. We can't lock the specification and make no changes, and neither can we go back in time and make different design decisions. Sorry, but I don't think there's much I can do. Long term we can migrate to the addon thing, but that's going to need the clients being changed as well.

The only client using this is AFAIK GNOME Software. To migrate long-term I would leave the bug open, so it doesn't get forgotten.
I am also leaving https://github.com/ximion/appstream/issues/195 open, where libappstream actually behaves according to the specification, but we might want to change the spec to be more strict (while I also con't immediately remove stuff without a deprecation phase).
