### ISSUE TITLE
Failure with Arch uncompressed packages

### ISSUE THREAD

**Issue by Carmina16** [hughsie/appstream-glib#264]
`appstream-glib` 0.7.12 seems to fail on Arch packages which are uncompressed:

    Failed to add package xxx-xxx-2-any.pkg.tar: No idea how to handle xxx-xxx-2-any.pkg.tar

If the package is compressed with `xz`, it seems to work fine.

**Comment by hughsie** [comment]
We're using alpm_pkg_load() -- https://github.com/hughsie/appstream-glib/blob/master/libappstream-builder/asb-package-alpm.c#L193 -- is that wrong?

**Comment by Carmina16** [comment]
I can see why:
```
if (g_str_has_suffix (filename, ".pkg.tar.xz"))
    pkg = asb_package_alpm_new ();
```
