### ISSUE TITLE
Support for ossp-uuid

### ISSUE THREAD

**Issue by ryandesign** [hughsie/appstream-glib#265]
Hi, appstream-glib (0.7.12) fails to build if [ossp-uuid](http://www.ossp.org/pkg/lib/uuid/) (1.6.2) is installed:

```
/opt/local/include/ossp/uuid.h:33:9: warning: '_XOPEN_SOURCE' macro redefined [-Wmacro-redefined]
#define _XOPEN_SOURCE 
        ^
<command line>:1:9: note: previous definition is here
#define _XOPEN_SOURCE 500
        ^
../appstream-glib-0_7_12/libappstream-glib/as-utils.c:1508:9: error: variable has incomplete type 'uuid_t' (aka 'struct uuid_st')
        uuid_t uu_namespace;
               ^
/opt/local/include/ossp/uuid.h:96:8: note: forward declaration of 'struct uuid_st'
struct uuid_st;
       ^
../appstream-glib-0_7_12/libappstream-glib/as-utils.c:1509:9: error: variable has incomplete type 'uuid_t' (aka 'struct uuid_st')
        uuid_t uu_new;
               ^
/opt/local/include/ossp/uuid.h:96:8: note: forward declaration of 'struct uuid_st'
struct uuid_st;
       ^
../appstream-glib-0_7_12/libappstream-glib/as-utils.c:1517:7: warning: implicit declaration of function 'uuid_parse' is invalid in C99 [-Wimplicit-function-declaration]
        rc = uuid_parse (namespace_id, uu_namespace);
             ^
../appstream-glib-0_7_12/libappstream-glib/as-utils.c:1541:2: warning: implicit declaration of function 'uuid_unparse' is invalid in C99 [-Wimplicit-function-declaration]
        uuid_unparse (uu_new, guid_new);
        ^
../appstream-glib-0_7_12/libappstream-glib/as-utils.c:1559:9: error: variable has incomplete type 'uuid_t' (aka 'struct uuid_st')
        uuid_t uu;
               ^
/opt/local/include/ossp/uuid.h:96:8: note: forward declaration of 'struct uuid_st'
struct uuid_st;
       ^
3 warnings and 3 errors generated.
```

Can support for ossp-uuid be added?

**Comment by hughsie** [comment]
I don't think ossp-uuid should be defining `_XOPEN_SOURCE` if it's already been defined. Are you also sure that ossp-uuid is fully compatible with the normal uuid.h?

**Comment by ryandesign** [comment]
> I don't think ossp-uuid should be defining `_XOPEN_SOURCE` if it's already been defined.

I don't have any information about that.

> Are you also sure that ossp-uuid is fully compatible with the normal uuid.h?

Well they certainly appear not to be compatible. But since ossp-uuid and libuuid serve similar functions—and both install a library named libuuid and a pkg-config file called uuid, so they conflict with one another—I've heard that other developers offer users the choice of which one to use. I've read that libuuid is more common on Linux while ossp-uuid is more common on BSD.

The reason for filing this issue today is described in https://trac.macports.org/ticket/57028. MacPorts standardized on using ossp-uuid. I could investigate switching everything in MacPorts to libuuid, and/or making ossp-uuid and libuuid not conflict there so that individual ports could use whichever one they want.

**Comment by hughsie** [comment]
> both install a library named libuuid and a pkg-config file called uuid

They need to stop doing that -- that's just crazy if the API is different. Looking at various packages in https://rpmfind.net it seems that most Linux packages rename the `uuid.pc` to `ossp-uuid.pc`.

> offer users the choice of which one to use

I don't think we want to support this, sorry.
