### ISSUE TITLE
appstream-compose fails to find icon when $prefix/usr exists 

### ISSUE THREAD

**Issue by BAKFR** [hughsie/appstream-glib#271]
I have an appstream file, a desktop file and an icon used as exports in a flapkak application. The appstream file references the desktop file. The desktop file uses the icon.

When `$prefix/usr` exists, `appstream-compose` requires the icon files to be in `$prefix/usr/share/icons` instead of `$prefix/share/icons`.

Flatpak is the use case I've encountered, but it's reproducible without it.

----

```sh
~/appstream-bug$ tree
.
├── share
│   ├── applications
│   │   └── org.example.TestIcon.desktop
│   ├── icons
│   │   └── hicolor
│   │       └── 256x256
│   │           └── apps
│   │               └── org.example.TestIcon.png
│   └── metainfo
│       └── org.example.TestIcon.appdata.xml
└── usr

~/appstream-bug$ appstream-compose --verbose --prefix=$(pwd) org.example.TestIcon
WARNING: Metadata origin not set, using 'example'
Processing application org.example.TestIcon
(appstream-compose:29789): As-DEBUG: Looking for /home/bak/appstream-bug/share/metainfo/org.example.TestIcon.appdata.xml
Error loading desktop file: Failed to find icon: Failed to find icon org.example.TestIcon
```

  

*org.example.TestIcon.desktop*:
```ini
[Desktop Entry]
Name=Test icon bug
Exec=/bin/sh
Icon=org.example.TestIcon
Type=Application
```

*org.example.TestIcon.appdata.xml*:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<component type="desktop-application">
  <id>org.example.TestIcon</id>
  <metadata_license>CC-BY-SA-3.0</metadata_license>
  <description>
  </description>
  <launchable type="desktop-id">org.example.TestIcon.desktop</launchable>
</component>
```

**Comment by BAKFR** [comment]
Flatpak uses `/app` as root prefix. appdata and icons are stored in `/app/share`.
Some libraries can be installed into `/app/usr/local/lib`, thus creating the `usr/` folder. It's the default config for Boost in Flatpak.

> The prefix is supposed to be `share`...

Do you mean I should execute `appstream-compose --prefix=$(pwd)/share org.example.TestIcon` in my example ?
It doesn't seem to work.

**Comment by hughsie** [comment]
> Some libraries can be installed into /app/usr/local/lib

That doesn't seem right. Surely for flatpak they should be installed into `app/lib`?

**Comment by BAKFR** [comment]
Yes, they probably should. There is no reason to use it, but it's not
forbidden either. Libraries using `$prefix/usr/local/lib` as default for
their install location will end up creating this folder.
In any case, I think it should be fixed, or at least an explanative error
message should be displayed.

**Comment by BAKFR** [comment]
I've looked a little into the code.

In `as-compose.c`, the default value for the prefix is `/usr`. The code expects the share folder to be `$prefix/share`. `as_utils_find_icon_filename_full($prefix, ...)` is called twice.


The function `as_utils_find_icon_filename_full(destdir, ...)` take a `destdir` argument that can be with either `NULL`, a root prefix like `/` or a prefix like `/usr`.
If `$destdir/usr` exists, it considers it a root prefix and uses `$destdir/usr/share`.

https://github.com/hughsie/appstream-glib/blob/89d3d99c10e58f7a312ff15f2ade20d584f21d7e/libappstream-glib/as-utils.c#L950-L954

Would you be interested in a pull request to search in both `$destdir/usr` and `$destdir` if these folders exists ?

**Comment by smcv** [comment]
> Libraries using `$prefix/usr/local/lib` as default for their install location will end up creating this folder

Why would a library do that? Normally they default to `$prefix/lib` (where `$prefix` itself defaults to `/usr/local`), or perhaps hard-code `/usr/lib` or `/usr/local/lib`. A library that defaulted to `$prefix/usr/local/lib` would install to `/usr/local/usr/local/lib` if built from source or `/usr/usr/local/lib` in a dpkg/rpm/etc. package, neither of which seems likely to be intentional.

**Comment by BAKFR** [comment]
I've verified, and indeed, it seems it was a mistake of mine. I've reused parts of a flatpak manifest found on Internet, using `-prefix=/app/usr/local/lib`.

**Comment by hughsie** [comment]
So we can close this bug now?

**Comment by BAKFR** [comment]
Well, my problem is resolved. Sorry if I didn't made it clear. 

However, I believe appstream-compose should handle this case, even if having an `/app/usr` folder has no meaning. Understanding that appstream-compose was failing because of the presence of this folder took me a long time, as the two points seems unrelated.
You can close this bug if you think it's not important.

I think I could make a patch for fixing this behaviour, if you want to.

**Comment by nedrichards** [comment]
Not sure it's an argument either way about the solution but this behaviour was unintuitive enough for basically the entire flathub maintencence team (and @hughsie ) to be stumped by it (and has now happened twice) so at the very least a more helpful error message would be useful.

**Comment by hfiguiere** [comment]
Lost many hours trying to figure out why appstream-compose failed with flathub/flathub#2296 (helping a contributor). I had to use `strace` to figure out that there was a `/app/usr`.

**Comment by hughsie** [comment]
> I had to use strace to figure out that there was a /app/usr.

I'd be fine to merge a patch that checks for DATADIR/usr existing.

**Comment by muelli** [comment]
@BAKFR expressed interest in providing a patch :)
