### ISSUE TITLE
validate output without hints for failing files

### ISSUE THREAD

**Issue by muelli** [hughsie/appstream-glib#277]
I get the following output of appstream-util for [this file](https://github.com/hughsie/appstream-glib/files/2712276/chat.delta.desktop.appdata.xml.gz): 
```
$ appstream-util validate-relax --nonet chat.delta.desktop.appdata.xml 
chat.delta.desktop.appdata.xml: FAILED:
• tag-invalid           : Expected children for tag
Validation of files failed
$ 
```

I have no clue what is failing and would appreciate some more hints in the default output such as the tag that is expecting children or the line and column of where it expected children.

**Comment by hughsie** [comment]
Can you attach the xml file to this issue please.

**Comment by muelli** [comment]
sure. I've done so. Here is the link again: https://github.com/hughsie/appstream-glib/files/2712276/chat.delta.desktop.appdata.xml.gz

FTR: I've found the kudos tag being the problem.

**Comment by hughsie** [comment]
This is tricky to fix as we're only setting a bitfield, rather than adding the problems to an array. I'll have a think, but it might mean refactoring the problems stuff out a bit.

**Comment by hughsie** [comment]
I don't know of an easy way to fix this, sorry. If you want to provide a patch I'm happy to review.

**Comment by muelli** [comment]
how about leaving this open s.t. an interested party with the necessary time and skill set can take a stab?
