### ISSUE TITLE
Add CSM ↔ OARS mappings for ages 16 and 17

### ISSUE THREAD

**Issue by pwithnall** [hughsie/appstream-glib#280]
See related: https://gitlab.gnome.org/GNOME/gnome-software/merge_requests/158

We’d like to be able to do a round trip from locale-specific ratings systems → CSM → OARS → CSM → locale-specific ratings system. The motivation behind this is to allow the user to choose an age rating for apps their child is allowed to install (using their locale’s rating system in gnome-control-center), store it on the child’s account as a set of OARS values (which can then be compared to the OARS values from any app they try to install), and re-load the UI from that set of OARS values the next time they open g-c-c.

Currently, round trips aren’t possible for all ratings systems, mostly because there are no CSM ↔ OARS mappings for ages 16 and 17. This means, for example, that OFLCNZ R16 is mapped to CSM age 16, which then maps back to CSM age 15 through the CSM ↔ OARS mappings. This then maps back to OFLCNZ R15, which is not what we started with.

I’m not sure where the original set of CSM ↔ OARS mappings came from (I can’t find information about them on the CSM site or the OARS site), so if this is not the right place to file this issue, I’m sorry.

**Comment by pwithnall** [comment]
With https://gitlab.gnome.org/GNOME/gnome-software/merge_requests/158 and https://gitlab.gnome.org/GNOME/gnome-software/merge_requests/159 applied, we have the following round trips:
```
(null) 3+ → 3 → 3 → 3+
(null) 7+ → 7 → 7 → 7+
(null) 12+ → 12 → 12 → 12+
(null) 16+ → 16 → 15 → 16+
(null) 18+ → 18 → 18 → 18+
INCAA ATP → 0 → 0 → ATP
INCAA +13 → 13 → 13 → +13
INCAA +18 → 18 → 18 → +18
ACB PG → 0 → 0 → PG
ACB MA15+ → 15 → 15 → MA15+
ACB R18+ → 18 → 18 → R18+
DJCTQ L → 0 → 0 → L
DJCTQ 10 → 10 → 10 → 10
DJCTQ 12 → 12 → 12 → 12
DJCTQ 14 → 14 → 14 → 14
DJCTQ 16 → 16 → 15 → 16
DJCTQ 18 → 18 → 18 → 18
GSRR 普通 → 0 → 0 → 普通
GSRR 保護 → 6 → 6 → 保護
GSRR 輔12 → 12 → 12 → 輔12
GSRR 輔15 → 15 → 15 → 輔15
GSRR 限制 → 18 → 18 → 限制
PEGI 3 → 3 → 3 → 3
PEGI 7 → 7 → 7 → 7
PEGI 12 → 12 → 12 → 12
PEGI 16 → 16 → 15 → 16
PEGI 18 → 18 → 18 → 18
KAVI 3+ → 3 → 3 → 3+
KAVI 7+ → 7 → 7 → 7+
KAVI 12+ → 12 → 12 → 12+
KAVI 16+ → 16 → 15 → 16+
KAVI 18+ → 18 → 18 → 18+
USK 0 → 0 → 0 → 0
USK 6 → 6 → 6 → 6
USK 12 → 12 → 12 → 12
USK 16 → 16 → 15 → 16
USK 18 → 18 → 18 → 18
ESRA +3 → 3 → 3 → +3
ESRA +7 → 7 → 7 → +7
ESRA +12 → 12 → 12 → +12
ESRA +15 → 15 → 15 → +15
ESRA +18 → 18 → 18 → +18
CERO A → 0 → 0 → A
CERO B → 12 → 12 → B
CERO C → 15 → 15 → C
CERO D → 17 → 15 → C (!!!)
CERO Z → 18 → 18 → Z
OFLCNZ G → 0 → 0 → G
OFLCNZ R13 → 13 → 13 → R13
OFLCNZ R15 → 15 → 15 → R15
OFLCNZ R16 → 16 → 15 → R15 (!!!)
OFLCNZ R18 → 18 → 18 → R18
RUSSIA 0+ → 0 → 0 → 0+
RUSSIA 6+ → 6 → 6 → 6+
RUSSIA 12+ → 12 → 12 → 12+
RUSSIA 16+ → 16 → 15 → 16+
RUSSIA 18+ → 18 → 18 → 18+
MDA General → 0 → 0 → General
MDA ADV → 16 → 15 → ADV
MDA M18 → 18 → 18 → M18
GRAC ALL → 0 → 0 → ALL
GRAC 12 → 12 → 12 → 12
GRAC 15 → 15 → 15 → 15
GRAC 18 → 18 → 18 → 18
ESRB Early Childhood → 0 → 0 → Early Childhood
ESRB Everyone → 6 → 6 → Everyone
ESRB Everyone 10+ → 10 → 10 → Everyone 10+
ESRB Teen → 13 → 13 → Teen
ESRB Mature → 17 → 15 → Mature
ESRB Adults Only → 18 → 18 → Adults Only
IARC 3+ → 3 → 3 → 3+
IARC 7+ → 7 → 7 → 7+
IARC 12+ → 12 → 12 → 12+
IARC 16+ → 16 → 15 → 16+
IARC 18+ → 18 → 18 → 18+
```

(`(null)` is for `GS_CONTENT_RATING_SYSTEM_UNKNOWN`, and is expected.)

**Comment by hughsie** [comment]
> might fix the problem

Are those not just missing, i.e. bugs? I'd say we just need to add both intense values!

**Comment by pwithnall** [comment]
> Are those not just missing, i.e. bugs?

You tell me. Where does this CSM ↔ OARS mapping come from?

**Comment by hughsie** [comment]
> Where does this CSM ↔ OARS mapping come from?

My wife studied Child Psychology. Using the constraints and social norms of CSM she went through each category with examples and she decided the age based on the CSM guidelines. I think what's happened is that we've added more "levels" of some attributes and not kept the CSM -> age table updated.

**Comment by hughsie** [comment]
@pwithnall are you prepping a PR for the missing intense values?

**Comment by pwithnall** [comment]
I am, but will include some tests too. It might take a few days.

**Comment by pwithnall** [comment]
PR available here: https://github.com/hughsie/appstream-glib/pull/283
