### ISSUE TITLE
Possible ABI break when updating appstream-glib from 0.7.14 to 0.7.15

### ISSUE THREAD

**Issue by Erick555** [hughsie/appstream-glib#295]
Hi!
In [freedesktop-sdk](https://gitlab.com/freedesktop-sdk/freedesktop-sdk) we're trying to keep ABI compatibility when updating elements like appstream-glib to new releases. In order to achieve this we use [libabigail](https://sourceware.org/libabigail/) tool to automate ABI compat checks. During appstream-glib update from 0.7.14 to 0.7.15 our tool produced following complaint:
```
┌─────────────────────────────────────────────────────┐
│ ABI Break: libappstream-glib.so.8:libappstream-glib │
└─────────────────────────────────────────────────────┘

Functions changes summary: 0 Removed, 2 Changed (7 filtered out), 0 Added (6 filtered out) functions
Variables changes summary: 0 Removed, 0 Changed, 0 Added variable
Variable symbols changes summary: 0 Removed, 0 Added variable symbol not referenced by debug info

2 functions with some indirect sub-type change:

  [C]'function void as_app_add_url(AsApp*, AsUrlKind, const gchar*)' at as-app.c:3817:1 has some indirect sub-type changes:
    parameter 2 of type 'typedef AsUrlKind' has sub-type changes:
      underlying type 'enum __anonymous_enum__' at as-enums.h:78:1 changed:
        type size hasn't changed
        3 enumerator insertions:
          '__anonymous_enum__::AS_URL_KIND_DETAILS' value '8'
          '__anonymous_enum__::AS_URL_KIND_SOURCE' value '9'
          '__anonymous_enum__::AS_URL_KIND_CONTACT' value '10'

        1 enumerator change:
          '__anonymous_enum__::AS_URL_KIND_LAST' from value '8' to '11' at as-enums.h:66:1


  [C]'function AsChecksumTarget as_checksum_get_target(AsChecksum*)' at as-checksum.c:182:1 has some indirect sub-type changes:
    return type changed:
      underlying type 'enum __anonymous_enum__' at as-checksum.h:59:1 changed:
        type size hasn't changed
        1 enumerator insertion:
          '__anonymous_enum__::AS_CHECKSUM_TARGET_DEVICE' value '4'

        1 enumerator change:
          '__anonymous_enum__::AS_CHECKSUM_TARGET_LAST' from value '4' to '5' at as-checksum.h:45:1
```
As part of our [discussion](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/merge_requests/1069) about what to do with that we would like to ask about your opinion on the matter. Especially I wanted to ask if reported change was intentional and if it's safe for backward compatibility thus if above report is a false positive.

I would be grateful if you can find time to respond. Thank you.

**Comment by hughsie** [comment]
The `_LAST` defines are not part of defined ABI. Most projects do something like this:

    AS_URL_KIND_CONTACT,		/* Since: 0.7.15 */
    /*< private >*/
    AS_URL_KIND_LAST

i.e. not a bug, sorry. If there's some kind of extra comment we can add to get the `_LAST` defines ignored by libabigail I'd be fine with that, but it probably should just read the gtk-doc comments as well.

**Comment by Erick555** [comment]
Ok, thank you for help.
