### ISSUE TITLE
appstream-util validate fails on example file from docs

### ISSUE THREAD

**Issue by notklaatu** [hughsie/appstream-glib#298]
Aside from having the same name as issue #230, I believe this is a different issue.

Using the example metadata file here:
https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps

```bash
$ appstream-util validate-relax org.gnome.gnome-power-statistics.appdata.xml
Error on line 2 char 2: Document must begin with an element (e.g. <book>
```

Change the ``<?xml ... ?>`` notation to ``<xml ... >`` and close the document with ``</xml>``

Also remove the comment on line 2 and try again:

```bash
$ appstream-util validate-relax org.gnome.gnome-power-statistics.appdata.xml
Error on line 4 char 7: <component> already set '​' and tried to replace with '  '
```
Licenses are on line 4, so try remove the licensing entirely..?

```bash
$ appstream-util validate-relax org.gnome.gnome-power-statistics.appdata.xml
Error on line 4 char 7: <component> already set '​' and tried to replace with '  '
```
No matter what, line 4 char 7 appears to be as far as appstream-util goes.

## System

$ grep PRETTY /etc/os-release 
PRETTY_NAME="Red Hat Enterprise Linux Workstation 7.6 (Maipo)"

$ appstream-util --version
Version:	0.7.8

**Comment by smcv** [comment]
> Change the `<?xml ... ?>` notation to `<xml ... >` and close the document with `</xml>`

That's certainly not valid: if the XML declaration `<?xml ... ?>` is causing a problem, the solution would be to delete it (and make sure the file is encoded in UTF-8), not to turn it into an unexpected XML element.

**Comment by notklaatu** [comment]
Yeah, tried that too. It still complains:

```bash
Error on line 1 char 1: Document must begin with an element (e.g. <book>)
```

**Comment by notklaatu** [comment]
And to confirm:

```bash
$ file org.gnome.gnome-power-statistics.appdata.xml 
org.gnome.gnome-power-statistics.appdata.xml: UTF-8 Unicode text
```

**Comment by ximion** [comment]
Very strange - can you attach the file you try to use to this bug report?

**Comment by notklaatu** [comment]
Sorry, looks like copy-pasting from the docs in Firefox introduced some unicode nonbreaking spaces. Getting rid of them has solved the problem.

Thanks for the help, I appreciate the fast response time!

**Comment by ximion** [comment]
Hmm, I wonder if there is some way to tell Publican to not use nonbreaking spaces in code blocks - those are really annoying, you aren't the first person who fell into that trap.
