### ISSUE TITLE
Error: <component> already set '?' and tried to replace with ' ?  '

### ISSUE THREAD

**Issue by berlogue** [hughsie/appstream-glib#30]
I've launched Opera Developer building at our KOJI server. The packages for F20 and F21 have been built succesfully. But package for F22-Rawhide has not been built. The following error was happened:

Error on line 5 char 7: <component> already set '?' and tried to replace with '  ?  '

Links:
http://koji.russianfedora.pro/koji/taskinfo?taskID=24241
https://github.com/RussianFedora/opera-developer

**Comment by ignatenkobrain** [comment]
I can confirm this bug. Before latest release it worked correctly. Also I
think this XML is valid.

**Comment by hughsie** [comment]
Hmm, I get:

    $ appstream-util validate-relax --nonet rfremix-opera-developer.appdata.xml 
    rfremix-opera-developer.appdata.xml: OK

xmllint doesn't see anything wrong with it either.

**Comment by ignatenkobrain** [comment]
I'm on rawhide with enabled koji repo

**Comment by berlogue** [comment]
I use F21, the verification is OK too. Well, KOJI builds F%{20|21} packages succesfully too. Apparently the issue is located at F22-Rawhide only. ignatenkobrain confirms this.

**Comment by berlogue** [comment]
Unfortunately the issue is still present at F22.

**Comment by ignatenkobrain** [comment]
@hughsie ping, we still see issue %)

**Comment by ignatenkobrain** [comment]
Hm, I don't see this error now. sry for mistake.
