### ISSUE TITLE
appstream-compose: Invalid desktop filename

### ISSUE THREAD

**Issue by eszlari** [hughsie/appstream-glib#308]
While trying to update Krita's flatpak to 4.2.0, I get the following error:

https://flathub.org/builds/#/builders/19/builds/498
```
Rewriting contents of org.kde.krita.desktop
Running appstream-compose
FB: Running: flatpak build --die-with-parent --nofilesystem=host /srv/buildbot/worker/build-x86_64-7/build/.flatpak-builder/rofiles/rofiles-8wDDYZ appstream-compose --prefix=/app --origin=flatpak --basename=org.kde.krita org.kde.krita
Processing application org.kde.krita
Invalid desktop filename: org.kde.krita
Error: ERROR: appstream-compose failed: Child process exited with code 1
FB: unmounting rofiles-fuse /srv/buildbot/worker/build-x86_64-7/build/.flatpak-builder/rofiles/rofiles-8wDDYZ
program finished with exit code 1
elapsedTime=5764.207692
```
I was able to built the alpha version of 4.2 successfully, so I don't know why it fails now. I have no idea how to debug this and don't see any problem with the file:
https://github.com/KDE/krita/blob/krita/4.2/krita/org.kde.krita.desktop

**Comment by hughsie** [comment]
Desktop names have to have a `.desktop` suffix to work. I don't believe the file would have no suffix, but perhaps you've a `<launchable>` in the appdata/,etainfo file without the suffix?

**Comment by smcv** [comment]
Looks like @hughsie's guess might be right: https://github.com/KDE/krita/blob/krita/4.2/krita/org.kde.krita.appdata.xml has

```
 <launchable type="desktop-id">org.kde.krita</launchable>
```

**Comment by hughsie** [comment]
Right, that's not a launchable.

**Comment by eszlari** [comment]
Thanks for spotting this!

Maybe `appstream-util validate` could catch this in the future?!
