### ISSUE TITLE
Offer suggestions when license full name is used instead of short name

### ISSUE THREAD

**Issue by hadess** [hughsie/appstream-glib#309]
When building Ghidra for Flatpak, I got:
> • tag-invalid           : <project_license> is not valid [Apache License 2.0]SPDX ID 'Apache License 2.0' unknown

Ideally, appstream-glib would have known about the full name, and offered up the short name as a suggestion:
https://spdx.org/licenses/Apache-2.0.html

So it would read:
>  • tag-invalid           : <project_license> is not a known short name [Apache License 2.0] use SPDX ID 'Apache-2.0' instead

**Comment by hughsie** [comment]
We don't know the long name, we only store the short version in the library. The long form is also less "API stable" than the SPDX tag, and so I don't think it's super possible to map back. Sorry.

**Comment by hadess** [comment]
Would be useful if it at least said that it needs to be a "license expression" which has a very defined format.

The tag name makes it look like free-form text, even if the spec mentions the "license expression" format.
