### ISSUE TITLE
appstream-util install-origin installs xml.gz files mode 600

### ISSUE THREAD

**Issue by DimStar77** [hughsie/appstream-glib#312]
Same as we already had in #21: with as-glib 0.7.15 (also tested 0.7.14, can't say about earlier), the files xml.gz files are being installed with mode 600, meaning a regular user can't read the XML files.

This in turn breaks things like appstream-util search (and most other things)

**Comment by DimStar77** [comment]
Different to last time we saw the issue, this time it actually does change the perms between source and dest (last time we just copied the source perms)

```
> ls -la /var/cache/zypp/raw/repo-oss/repodata/
-rw-r--r-- 1 root root  3807499 Jul 26 13:32 a3105287d6ecc946e86b03de90273d25266520e966bd4de7b646602cc25c4a27-appdata-icons.tar.gz
-rw-r--r-- 1 root root  3899768 Jul 26 13:32 bad5d8f6d991082904a2f790ccfb5eb34e0411b6c823c604db66b704853393ef-appdata.xml.gz
```

```sudo appstream-util install-origin TEST /var/cache/zypp/raw/repo-oss/repodata/bad5d8f6d991082904a2f790ccfb5eb34e0411b6c823c604db66b704853393ef-appdata.xml.gz /var/cache/zypp/raw/repo-oss/repodata/a3105287d6ecc946e86b03de90273d25266520e966bd4de7b646602cc25c4a27-appdata-icons.tar.gz```

```
> ls -la /var/cache/app-info/xmls/
-rw------- 1 root root 3872717 Jul 27 10:08 TEST.xml.gz
```

**Comment by hughsie** [comment]
I you change `G_FILE_CREATE_NONE` to `G_FILE_CREATE_REPLACE_DESTINATION` in the call to `g_file_replace_contents()` in `as_store_to_file()` does that fix things? Also, what is creating `/var/cache/app-info` -- are the permissions being inherited from that?

**Comment by JonathanKang** [comment]
Latest fedora 30 has the same issue. Permission denied while doing `appstream-util search foobar` for appstream files under `/var/cache/app-info/xmls/`.

**Comment by JonathanKang** [comment]
Tested with commit cce5103. It fixes this issue.
