### ISSUE TITLE
appstream-util thinks I live in the future

### ISSUE THREAD

**Issue by whot** [hughsie/appstream-glib#317]
Looks like fallout from #153 

If I put today's release date into the appdata file, I can't get past the CI checks until UTC ticks past midnight. Reason is that appstream-util thinks anything not UTC is the future which is both philosophically and technically incorrect. 

So those sad people that live in, say, UTC+10 have to wait until it's 10 am before they can release anything. I can't even imagine the sadness that would befall the kiwis given they aren't allowed to use today's date until lunchtime or later (they use DST which not all Australians are capable of, so who knows what their wall clock time is at any point). They may already be a pint or two in by then, so I'm not sure releasing is a smart thing to do after that.

Now, this is of course a situation we in the east face commonly, on acount that we are not many (compared to the millions of europeans and americans,  those 2 billion people in china and india are less than ... wait, nevermind). We could just put in yesterdays date but that feels wrong. Imagine the roar if the Americans would be forced to put tomorrows date in. I suspect they wouldn't be able to live the fear of potentially wrecking the time-space continuum - you can't release anything tomorrow if you're not sure tomorrow happens. Future alien archaeologists will be confused picking through the ruins of a civilization that fell apart but somehow managed to push to flathub on the day after everything died. 

Anyway. A simple solution would be to subtract `13 * 60 * 60` from the timestamp in   `as_app_validate_release()`, that should cater for any +12 DST timezones I think.

However, if you say "live with it" I'll accept that answer too. Especially because now the clock ticked past 10 am and I can continue anyway :)

**Comment by hughsie** [comment]
> A simple solution would be to subtract 13 * 60 * 60 from the timestamp in as_app_validate_release()

Sounds sane. Could you do a PR for that please and I can get it in the next release. Thanks!
