### ISSUE TITLE
Any plans to make new release?

### ISSUE THREAD

**Issue by kloczek** [hughsie/appstream-glib#326]
I think that it would be good to flush currently committed changes and make new release :)

**Comment by hughsie** [comment]
I'm just waiting for https://github.com/hughsie/appstream-glib/pull/325

**Comment by uajain** [comment]
New release available - `appstream_glib_0_7_16 `

I have a [wip branch](https://gitlab.gnome.org/uajain/appstream-glib/commits/master) for pushing the release intro debian packaging branches. Should be available in next few days.

P.S. The issue can be closed now. I don't have enough rights to close.

**Comment by kloczek** [comment]
Just suggestion.
If you could change tagging convention to version like 0.7.16 you will have less work to do because dist tar ball ready to use by packagers will be possible download straight from https://github.com/hughsie/appstream-glib/archive/0.7.16.tar.gz
Majoryty of the projects now is now using that kind convention.
I have running automation which grabs automatically new tar balls from tags to package. It project tag is just plain version it creates easiest way to connect work of the people like you with other layer on which I'm working.

Please consider change tagging convention in the the future :)
