### ISSUE TITLE
Package appstream-glib-0.7.16

### ISSUE THREAD

**Issue by uajain** [hughsie/appstream-glib#327]
From #debian-gnome:
```
<uajain> Pinging again if someone could help me out with wip branch of packaging appstream-glib https://gitlab.gnome.org/uajain/appstream-glib/commits/master
<Laney> uajain: we don't maintain that in this team
<Laney> try contacting ximion directly, for example via a bug report on the package
<uajain> oh. I see. 
<uajain> Thanks.
```

@ximion I have a wip branch [here](https://gitlab.gnome.org/uajain/appstream-glib/commits/master) which I made by reading the older packaging commits. I have having blockers in understanding how "tags" exactly works among  `upsream` , `master` and `debian/version-x` branches. 

Apart from that, I didn't understand how to get tree commit-id of `debian/` directory. See this commit [here](https://gitlab.gnome.org/uajain/appstream-glib/commit/bc922773f6b2586dfc34d6ace906c5260ad99529). Can you help resolve these blockers so that it can be landed in debian-salsa.

**Comment by uajain** [comment]
Release done: https://salsa.debian.org/pkgutopia-team/appstream-glib/commits/debian/0.7.16-1

Thanks!

**Comment by ximion** [comment]
Oh, I just saw this! Sorry for not replying earlier!
In general, please submit a pull-request on Salsa for code changes, or file a bug at the Debian BTS, that way I will see changes for sure and definitely in time.
For new upstream releases, I usually don't want "direct" PRs though, as they affect multiple branches and are a bit messy to handle. Usually a `gbp import-orig --uscan` is much better in those cases.
Thanks for looking into this though!
