### ISSUE TITLE
new "icon-theme" component type not recognised

### ISSUE THREAD

**Issue by decathorpe** [hughsie/appstream-glib#331]
`icon-theme` is apparently an acceptable component type now:

https://www.freedesktop.org/software/appstream/docs/sect-Metadata-IconTheme.html

I'm packaging the elementary icons for fedora, and they now ship an appdata file which uses this type, but the file doesn't validate correctly in fedora.

**Comment by hughsie** [comment]
If you can do a PR, I'll review it and do a new tarball for Fedora. Thanks.
