### ISSUE TITLE
please migrate to the new Fedora translation platform

### ISSUE THREAD

**Issue by Jibec** [hughsie/appstream-glib#339]
Hello, the Fedora project migrates its translation platform to Weblate [1].

This tool directly interact with your git repository, and requires us to know:
* [mandatory] which branch is your development branch?
* [mandatory] have you merged latest translation from Zanata and locked the project?
* [info] Weblate will handle updates when pot file changes, don't edit po files for this [2]
* [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)
* [optional] do you have any announcement/warning you would like to display to the translators? (it will be displayed in Weblate)
* [optional] do you need us to activate any specific checks? (this is a setting per component [3])
* [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)

Please note:
* For github hosted projects, Weblate open pull request. For other project, you'll have to add a key to allow commits.
* In Weblate's vocable, one project is a group of component. Each component is a translation file. You can have many projects or many components or both.
* You can change your mind over time, just reach trans@lists.fedoraproject.org

[1] https://communityblog.fedoraproject.org/fedora-localization-platform-migrates-to-weblate/ 
[2] https://docs.weblate.org/en/latest/admin/continuous.html#avoiding-merge-conflicts
[3] https://docs.weblate.org/en/latest/user/checks.html#translation-checks

**Comment by Jibec** [comment]
action to do on your side:
1. lock your zanata project and merge latest translations: https://fedora.zanata.org/project/view/appstream-glib
2. commit the pot file and make sure it will be generated in the future
3. log one time to https://translate.stg.fedoraproject.org/

then I'll do configuration of your project on weblate and make you admin on it

then, we'll close this issue :)

**Comment by hughsie** [comment]
If I'm honest, I was thinking of going back to transifex...

**Comment by Jibec** [comment]
That's fine for me, it's your project.

**Comment by Jibec** [comment]
I'm closing this. 
Either you'll close the zanata project yourself or you can wait for the platform to die.

You are welcome to try Weblate at any time, just reopen this issue.
