### ISSUE TITLE
Incorrect min glib version in meson.build

### ISSUE THREAD

**Issue by aclemons** [hughsie/appstream-glib#341]
[meson.build](https://github.com/hughsie/appstream-glib/blob/appstream_glib_0_7_16/meson.build#L62) says the min glib version is 2.45.8. [as-app-desktop.c](https://github.com/hughsie/appstream-glib/blob/appstream_glib_0_7_16/libappstream-glib/as-app-desktop.c#L519) however uses g_key_file_load_from_bytes which was added to glib 2.49.3 (see [NEWS](https://gitlab.gnome.org/GNOME/glib/blob/2.49.3/NEWS#L9)). Additionally [as-format.c](https://github.com/hughsie/appstream-glib/blob/appstream_glib_0_7_16/libappstream-glib/as-format.c#L197) uses g_canonicalize_filename which was added in 2.58 ([commit](https://gitlab.gnome.org/GNOME/glib/commit/b9b642de06e714584e89aa7b8d878a98599538ed#c0e40c6287fb64a7a3d8c9fa35b5e014025da233_175_175))

Thanks

**Comment by hughsie** [comment]
Would you be able to do a PR for this please? I guess 2.58.0 is what we want.

**Comment by aclemons** [comment]
Opened now, sorry for the delay.
