### ISSUE TITLE
validate: No error on incorrect launchable types

### ISSUE THREAD

**Issue by imciner2** [hughsie/appstream-glib#368]
When the appstream.xml file has an incorrect launchable type (such as `desktop` instead of `desktop-id`), running appstream-util validate (or validate-relax or validate-strict) does not warn that an invalid launchable type is used. This actually leads to problems, since the launchable type must be correct for the appstream-builder metadata generation to work properly (see this bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1810509).

Sample appdata file that shows this:
```
<?xml version="1.0" encoding="UTF-8"?>
<component>
  <id>com.example.foobar</id>
  <name>Foo Bar</name>
  <summary>A foo-ish bar</summary>
  <url type="homepage">http://www.example.org</url>
  <metadata_license>CC0-1.0</metadata_license>
  <launchable type="desktop">test.desktop</launchable>

  <provides>
    <library>libfoobar.so.2</library>
    <font>foo.ttf</font>
    <binary>foobar</binary>
  </provides>
  <releases>
    <release version="1.2" date="2015-02-16" />
  </releases>
  <developer_name>FooBar Team</developer_name>
</component>
```

The errors given on the different settings are:
```
$ appstream-util validate test.appdata.xml 
test.appdata.xml: FAILED:
• style-invalid         : Not enough <screenshot> tags, minimum is 1
Validation of files failed

$ appstream-util validate-relax test.appdata.xml 
test.appdata.xml: OK

$ appstream-util validate-strict test.appdata.xml 
test.appdata.xml: FAILED:
• tag-missing           : <project_license> is not present
• tag-missing           : <translation> not specified
• tag-missing           : <update_contact> is not present
• value-missing         : <!-- Copyright [year] [name] --> is not present
• style-invalid         : Not enough <screenshot> tags, minimum is 1
• translations-required  : <name> has no translations
• translations-required  : <summary> has no translations
Validation of files failed
```
but none of them mention the incorrect launchable type.

**Comment by hughsie** [comment]
> but none of them mention the incorrect launchable type

Good find! Would you be able to attempt a pull request to fix this please? It should be quite a simple fix in `libappstream-glib/as-app-validate.c` an most of the code and be copy-pasted from the other validation modes. Thanks.
