### ISSUE TITLE
appstream-util install-origin no longer seems to work

### ISSUE THREAD

**Issue by DimStar77** [hughsie/appstream-glib#37]
As openSUSE newly has the appdata.xml.gz and appdata-icons.tar.gz published in the repository data (autogenerated on creating the published tree), I wanted to work further on using installing those in the end on machines.

For this, install-origin was introduced earler (as ALL repos would end up with an appdata.xml.gz, we cannot simply install the file; it needs to be renamed and updated, which was what install-origin would do).

with a 'valid' appdata.xml.gz and appdata-icons.tar.gz in $PWD (both files generated by appstream-builder), all I get is:

#> ls /usr/share/app-info/xmls/
#> appstream-util -v install-origin Tumbleweed appdata.xml.gz appdata-icons.tar.gz
#> ls /usr/share/app-info/xmls/
#>

**Comment by hughsie** [comment]
Noise :)
