### ISSUE TITLE
Make check fails on ppc64

### ISSUE THREAD

**Issue by DimStar77** [hughsie/appstream-glib#38]
Running make check on a PPC64 build host results in

[   96s] make  check-TESTS
[   96s] make[3]: Entering directory '/home/abuild/rpmbuild/BUILD/appstream-glib-0.3.5/libappstream-builder'
[   96s] make[4]: Entering directory '/home/abuild/rpmbuild/BUILD/appstream-glib-0.3.5/libappstream-builder'
[   96s] ../test-driver: line 107: 11605 Aborted                 "$@" > $log_file 2>&1
[   96s] FAIL: asb-self-test
[   96s] ============================================================================
[   96s] Testsuite summary for appstream-glib 0.3.5
[   96s] ============================================================================
[   96s] # TOTAL: 1
[   96s] # PASS:  0
[   96s] # SKIP:  0
[   96s] # XFAIL: 0
[   96s] # FAIL:  1
[   96s] # XPASS: 0
[   96s] # ERROR: 0
[   96s] ============================================================================
[   96s] See libappstream-builder/test-suite.log
[   96s] ============================================================================
[   96s] Makefile:1253: recipe for target 'test-suite.log' failed
[   96s] make[4]: *** [test-suite.log] Error 1
[   96s] make[4]: Leaving directory '/home/abuild/rpmbuild/BUILD/appstream-glib-0.3.5/libappstream-builder'
[   96s] Makefile:1359: recipe for target 'check-TESTS' failed
[   96s] make[3]: *** [check-TESTS] Error 2
[   96s] make[3]: Leaving directory '/home/abuild/rpmbuild/BUILD/appstream-glib-0.3.5/libappstream-builder'
[   96s] Makefile:1457: recipe for target 'check-am' failed
[   96s] make[2]: *** [check-am] Error 2
[   96s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/appstream-glib-0.3.5/libappstream-builder'
[   96s] Makefile:1146: recipe for target 'check-recursive' failed
[   96s] make[1]: *** [check-recursive] Error 1
[   96s] make[1]: Leaving directory '/home/abuild/rpmbuild/BUILD/appstream-glib-0.3.5/libappstream-builder'
[   96s] Makefile:538: recipe for target 'check-recursive' failed
[   96s] make: *** [check-recursive] Error 1
[   96s] error: Bad exit status from /var/tmp/rpm-tmp.MLBRLV (%check)

I will try to change the build bot to spit out the log mentioned in the error

**Comment by DimStar77** [comment]
As promised:

[   95s] + cat libappstream-builder/test-suite.log
[   95s] ===============================================================
[   95s]    appstream-glib 0.3.5: libappstream-builder/test-suite.log
[   95s] ===============================================================
[   95s] 
[   95s] # TOTAL: 1
[   95s] # PASS:  0
[   95s] # SKIP:  0
[   95s] # XFAIL: 0
[   95s] # FAIL:  1
[   95s] # XPASS: 0
[   95s] # ERROR: 0
[   95s] 
[   95s] .. contents:: :depth: 2
[   95s] 
[   95s] FAIL: asb-self-test
[   95s] ===================
[   95s] 
[   95s] /AppStreamBuilder/package: OK
[   95s] /AppStreamBuilder/utils{replace}: OK
[   95s] /AppStreamBuilder/utils{glob}: OK
[   95s] /AppStreamBuilder/plugin-loader: GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
[   95s] OK
[   95s] /AppStreamBuilder/firmware: Processing packages...
[   95s] Merging applications...
[   95s] Writing /tmp/asbuilder/output/appstream.xml.gz...
[   95s] Writing /tmp/asbuilder/output/appstream-icons.tar.gz...
[   95s] **
[   95s] Asb:ERROR:asb-self-test.c:980:asb_test_firmware_func: assertion failed (as_store_get_size (store) == 1): (0 == 1)
[   95s] FAIL asb-self-test (exit status: 134)

**Comment by hughsie** [comment]
Can you get the log with export G_MESSAGES_DEBUG="all" please? Also, is this the 0.3.5 release tarball? Thanks.

**Comment by hughsie** [comment]
Also, all the appstream* files in /tmp/asbuilder/output/ would be great, thanks.

**Comment by DimStar77** [comment]
I can surely create the log with more messages (I hope).. getting the files in /tmp is more difficult, as they are in a shielded off build bot. I can try to reproduce this in a local VM... (but then I need to cross-build, instead of native build)

**Comment by hughsie** [comment]
I'm a bit confused why it's failing given that firmware is supposed to be arch-neutral.

**Comment by DimStar77** [comment]
https://build.opensuse.org/package/live_build_log/GNOME:Next/appstream-glib/openSUSE_PPC/ppc64 contains a log output with debug enabled (and yes, this is the 0.3.5 release; actually based of a git clone at the tag, not the tarball)

**Comment by DimStar77** [comment]
looking at 
WARNING: Failed to explode: Cannot extract: Checksum error CFDATA[0] c26bbe02:12bb6ed2 in 465 bytes

it might actually be an issue of gcab?

**Comment by hughsie** [comment]
We're using gcab to create the .cab files used in the self test. The actual decompression is done by libarchive in the builder. To find out if it's a gcab or libarchive we'd have to get a copy of the built data/tests/colorhug-als-2.0.2.cab and then try to decompress that on a !ppc64 machine. If it decompresses fine, it's a libarchive issue, if it's corrupt, it's a gcab issue.

**Comment by DimStar77** [comment]
FYI: bgo#746580 seems to address the issue (got a gcab with the patch applied and appstream-glib passes the test suite on all archs now for me)

**Comment by hughsie** [comment]
Great, thanks for testing.
