### ISSUE TITLE
feature: create table to perform screenshot sync post appdata building

### ISSUE THREAD

**Issue by DimStar77** [hughsie/appstream-glib#40]
Due to the current way openSUSE interated appstream-builder directly into the repo publishing process (same step createrepo is being started), the bot is generally isolated from the network, and appstream-builder is being executed without network access (--no-net)

due to this, it creates an appdata.xml.gz without any screenshot tags (sad)

I'd like to see an option that appstream-builder produces an additional download-map:remote URL file (remote-URL based on the screenshot-url

so that this map file could be taken to the 'screenshot hosting server' and the screenshots be sync'ed there directly (with information of source and expected destination in the hosted tree)

The result should be:
* appdata.xml.gz contains screenshot URLs linking to the 'openSUSE screenshot host'
* a map file put next to the appdata.xml.gz, which we can move over to the openSUSE screenshot host' and sync the screenshots based on this (drop 'no longer listed ones, download new ones)

appstream-builder is already now started with:
--no-net \
--screenshot-uri=http://static.opensuse.org/screenshots

so the URL to put into the .xml file should be available.

**Comment by hughsie** [comment]
Does the mirror-screenshots command in appstream-util fix this?

**Comment by hughsie** [comment]
I'm using mirror-screenshots in Fedora for this. Please reopen if this doesn't work for you.

**Comment by DimStar77** [comment]
Will have to re-check this.. but IIRC it did not work, as it wanted to download and update the appdata.xml.gz at the same time - thus changing the already published repodata
