### ISSUE TITLE
appstreamcli validate erroneously represents deprecation warning as validation failure

### ISSUE THREAD

**Issue by marcusmueller** [hughsie/appstream-glib#404]
We're using `appstreamcli validate` in our CI. False positives hence eat FOSS volunteer developer efficiency.

```xml
<url type="contact">mailto:discuss-gnuradio@gnu.org</url>
```

is **[deprecated](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#id-1.3.6.4.3.8.2.2.7.2.3)**:

> In the past, mailto: URL schemas to link to email addresses were also supported for this URL type. **It is recommended** to not use them in **new** metadata, as they provide poor usability on most systems when users click on such a link and no local email client is configured. 

(emphasis mine) 

# expected behaviour

A *recommendation not to do something in a new file* is certainly worth an informative output, or a warning, but not an error.

# actual behaviour

```shell
$> appstreamcli validate --no-net /home/marcus/src/gnuradio/grc/scripts/freedesktop/org.gnuradio.grc.metainfo.xml || echo "returned error code"
E: org.gnuradio.grc:53: web-url-expected mailto:discuss-gnuradio@gnu.org

Validation failed: errors: 1
returned error code
```

appstreamcli fails to validate this valid file. Note that I'm not using `--pedantic`.

**Comment by vchernin** [comment]
this repo is appstream-glib, you want this one https://github.com/ximion/appstream

**Comment by McTrk** [comment]
This bug comes with libappstream-glib and fails as follows:
```
$ appstream-util validate-relax --nonet orig/emacs.metainfo.xml
orig/emacs.metainfo.xml: FAILED:
? tag-invalid           : <url> type invalid [unknown]
Validation of files failed
$ appstream-util validate-relax --nonet fixed/emacs.metainfo.xml
fixed/emacs.metainfo.xml: OK
$ diff {orig,fixed}/emacs.metainfo.xml 
35c35
<  <url type="contact">https://lists.gnu.org/mailman/listinfo/emacs-devel/</url>
---
>  <!-- url type="contact">https://lists.gnu.org/mailman/listinfo/emacs-devel/</url -->

$ yum whatprovides $(which appstream-util)
libappstream-glib-0.7.8-2.el7.x86_64 : Library for AppStream metadata
Repo        : @anaconda/7.9
Matched from:
Filename    : /usr/bin/appstream-util
...
$ 
```

**Comment by hughsie** [comment]
> Too many dependencies make it difficult to build and verify on Centos 7.9.

I don't think that's an upstream issue.

**Comment by McTrk** [comment]
> > Too many dependencies make it difficult to build and verify on Centos 7.9.
> 
> I don't think that's an upstream issue.

Fair enough. Patched two files manually and rebuilt the rpm locally. No worries.
