### ISSUE TITLE
appstream-util uninstall does not remove from /var/cache

### ISSUE THREAD

**Issue by DimStar77** [hughsie/appstream-glib#42]
Installing appstream data using appstream-util install-origin installs rhe metadata to /var/cache/app-info

appstream-util uninstall though does not attempt to remove metadata from there and simply says metadaa not found.

**Comment by hughsie** [comment]
Can you test this patch please: http://people.freedesktop.org/~hughsient/temp/0001-Allow-uninstalling-AppStream-files-from-var-cache.patch

**Comment by DimStar77** [comment]
Patch seems to be working in my tests.
