### ISSUE TITLE
Update license list to include OFL-1.1-RFN

### ISSUE THREAD

**Issue by marksvc** [hughsie/appstream-glib#435]
The file libappstream-glib/as-license-ids.txt is missing "OFL-1.1-RFN", and so when validating metadata, there an error, such as the following. Could the list be updated so that this license is not unknown?

> • tag-invalid           : <project_license> is not valid [... OFL-1.1-RFN]SPDX ID 'OFL-1.1-RFN' unknown
> Validation of files failed

**Comment by hughsie** [comment]
Got a patch? Thanks.
