### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by JakobDev** [hughsie/appstream-glib#444]
The new URL types `vcs-browser` and `contribute` URL types were added in #438, which is not included in a release yet. They are already used by some Apps. But if a App uses them, `appstream-compose` does not just ignore thme, it will fail. This is a Big problem for Flatpak now. Flathub uses a newer commit of appstream-glib instead of the latest release, so it will work there. But on a normal PC, which uses the latest release of appstream-glib, the Build will fail. See flatpak/flatpak-builder#480. There are a workaround by using the patched version from Flathub, but this should not be the solution. People who try to build a Flatpak for a App which has the new URL types will likely use the normal `flatpak-builder` insteda of the patched one from Flathub, which causes the whole Build to fail. 

To address this Issue, please make a new Release soon, so the Distros can ship it. It would be not a Problem, if the new types would just be ignored, but they cause the Build to fail. This is currently a Big Issue and needs to be addressed as soon as possible.

**Comment by hughsie** [comment]
It's already on my list for today for the GNOME release.

**Comment by JakobDev** [comment]
I see, the new release is now out. Thanks.

**Comment by ximion** [comment]
You probably know this already, but appstream-glib is missing a lot more than just the two URL types by now, unfortunately, like new tags for `releases` and especially a lot of the relation items (`suggests`/`supports`, etc.)
The URL types are probably some of the most visible omissions by now.

**Comment by JakobDev** [comment]
I know that. An it's really time for Flatpak to switch to libappstream to fix the Issues, but it will looks like it will still take some time. The big problem here is, that the Flatpak build fails with a AppStream error when there is a URL type that does not exists.  The other Tags that appstream-glib does not know are simply ignored (as it should be) and did not cause a build error. So this new release is more an important Hotfix than a long term solution.
