### ISSUE TITLE
as-self-test fails since 0.8.0

### ISSUE THREAD

**Issue by heftig** [hughsie/appstream-glib#445]
The `as-self-test` fails since 0.8.0:

```
<It now also supports<em>em</em><code> and </code><code>code</code> tags.>
Bail out! As:ERROR:../appstream-glib/libappstream-glib/as-self-test.c:2944:as_test_node_xml_func: assertion failed (as_node_get_data (n2) == "It now also supports<em>em</em> and <code>code</code> tags."): ("It now also supports<em>em</em><code> and </code><code>code</code> tags." == "It now also supports<em>em</em> and <code>code</code> tags.")
stderr:
**
As:ERROR:../appstream-glib/libappstream-glib/as-self-test.c:2944:as_test_node_xml_func: assertion failed (as_node_get_data (n2) == "It now also supports<em>em</em> and <code>code</code> tags."): ("It now also supports<em>em</em><code> and </code><code>code</code> tags." == "It now also supports<em>em</em> and <code>code</code> tags.")
```

Bisection identified f939f14774618fd07d7019e9d0c86e1e1ae5642a as the first broken commit.

`meson setup` + `compile` log: [appstream-glib-0.8.0-1-x86_64-build.log](https://github.com/hughsie/appstream-glib/files/9121597/appstream-glib-0.8.0-1-x86_64-build.log)
`meson test` log: [appstream-glib-0.8.0-1-x86_64-check.log](https://github.com/hughsie/appstream-glib/files/9121588/appstream-glib-0.8.0-1-x86_64-check.log)

**Comment by hughsie** [comment]
It worked here (and continues to work); can you debug a bit please?

**Comment by heftig** [comment]
The new fields in the `AsNodeToXmlHelper` struct aren't being initialized.

(Also, they should probably be bitfields for consistency.)

**Comment by hughsie** [comment]
Can you do a pr please?
