### ISSUE TITLE
appstream-util install(-origin) should only install valid appdata.xml

### ISSUE THREAD

**Issue by DimStar77** [hughsie/appstream-glib#46]
I just ran into the 'issue' that GNOME Software showed me weird descriptions of apps, in all kind of languages.

Turned out, one repository published invalid metadata (not generated using appstream-builder), thus spoiling the reputation of GNOME-Software as a reliable front end.

I since implemented in the libzypp plugin handlng appstream metadata, that only files passing appstream-util validate-relax are being considered to be installed. The others have sufficiently severe issues that they should be ignored (style issues have been removed from being fatal for validate-relax just recently, for the same use case)

it would be great if install(-origin) would handle that directly, instead of passing the same .xml file to two parsers in sequence.

**Comment by hughsie** [comment]
So install-origin should validate the file before installing?

**Comment by DimStar77** [comment]
I think that would be good - currently we use this script to install appdata.xml from the repo download cache to the actual places:

https://build.opensuse.org/package/view_file/GNOME:Next/libzypp-plugin-appdata/InstallAppdata.sh?expand=1

**Comment by hughsie** [comment]
GNOME Software does a much better job for invalid files now; it doesn't just fall on it's face. :)
