### ISSUE TITLE
appstream-util: deal with duplicate data

### ISSUE THREAD

**Issue by DimStar77** [hughsie/appstream-glib#47]
I seem to have an issue with the 'inhouse generator' (nor asb) putting apps duplictae into the appstream.xml.gz file...

certainly not nice, but it should also not really be an issue, should it?

If it were, I would expect appstream-util validate-relax to complain about more things than just:
• duplicate-data        : pidgin.desktop: <screenshot> has duplicated data
• duplicate-data        : pitivi.desktop: <screenshot> has duplicated data
• duplicate-data        : rhythmbox.desktop: <screenshot> has duplicated data
• duplicate-data        : shotwell.desktop: <screenshot> has duplicated data
• duplicate-data        : transmageddon.desktop: <screenshot> has duplicated data
• duplicate-data        : zim.desktop: <screenshot> has duplicated data

Yet for the screenshots it does complain, which renders the entire validation process 'failed'.
Is this intentional?

**Comment by hughsie** [comment]
Have you got an example please? I assume it's duplicate <component> with the same ID you mean. In general AsStore just merges duplicate data, although does check (quite rightly) for duplicate screenshots and releases.

**Comment by DimStar77** [comment]
http://download.opensuse.org/repositories/GNOME:/Apps/openSUSE_Factory/repodata/?P=*appdata.xml.gz

**Comment by hughsie** [comment]
The thing is, duplicated IDs in an AppStream file is something that really *should* fail validation. libappstream-glib happens to accept it and kinda do the right thing, but other libraries exist that parse the files too.

**Comment by DimStar77** [comment]
Thibg is, it does not complain about the IDs, but about the screenshot... Quite an arbitrary attribute of a component.

Sent from my Sony Xperia™ smartphone

---- Richard Hughes wrote ----

**Comment by hughsie** [comment]
I think this is better now, right?

**Comment by DimStar77** [comment]
Duplicate screenshots are still conidered failure in validate-relax (tested with 0.5.1)

**Comment by DimStar77** [comment]
1fe19d97dc4737134adf38d67a08fb490aa50c91d97344d75d9ac9ed9daf9690-appdata.xml.gz: FAILED:
• duplicate-data        : nm-connection-editor.desktop: <screenshot> has duplicated data
• duplicate-data        : org.gnome.Dictionary.desktop: <screenshot> has duplicated data
• duplicate-data        : gpk-application.desktop: <screenshot> has duplicated data
• duplicate-data        : gpk-update-viewer.desktop: <screenshot> has duplicated data

**Comment by DimStar77** [comment]
when not doing -relaxed, then the error is clearer:
• duplicate-data        : gpk-application.desktop: <screenshot> has duplicated data
• duplicate-data        : gpk-update-viewer.desktop: <screenshot> has duplicated data

**Comment by hughsie** [comment]
I think that's the right behaviour for a validator, sorry.
