### ISSUE TITLE
Please add more values to enum AsAppState

### ISSUE THREAD

**Issue by rluzynski** [hughsie/appstream-glib#52]
Please add these values to the ```enum AsAppState``` corresponding to some ```enum PkInfoEnum``` values:

Requested ```AsAppState``` values | Existing ```PkInfoEnum``` values
------------------------------------------|---------------------------------
```AS_APP_STATE_UPDATING``` | ```PK_INFO_ENUM_UPDATING```
```AS_APP_STATE_REINSTALLING``` | ```PK_INFO_ENUM_REINSTALLING```
```AS_APP_STATE_DOWNGRADING``` | ```PK_INFO_ENUM_DOWNGRADING```
```AS_APP_STATE_UNTRUSTED``` | ```PK_INFO_ENUM_UNTRUSTED```

I need them for https://bugzilla.gnome.org/show_bug.cgi?id=711171.

**More details:** I'm going to use ```PkTask``` in simulate mode. It provides a list of dependent packages which will also be changed during the current transaction. The action which would be taken on every dependent package is returned by ```pk_package_get_info ()``` and it may be one of some ```PK_INFO_ENUM_...``` values, an example is [```pk_task_text_simulate_question_type_to_string ()```](https://github.com/hughsie/PackageKit/blob/master/lib/packagekit-glib2/pk-task-text.c#L296). (Actually, I can't imagine why ```REINSTALLING``` or ```UNTRUSTED``` should be returned but I can easily imagine examples when a package will be updated or downgraded.) Then I'm going to convert a list of ```PkPackage``` to a list of ```GsApp``` using [```gs_plugin_packagekit_add_results ()```](https://git.gnome.org/browse/gnome-software/tree/src/plugins/packagekit-common.c#n91) to have the high quality and translated names of the packages as well as to be able to check whether a package is an application, an add-on, a core system component which cannot be removed, or a less important system component. This function is not perfect because [it only recognizes ```PK_INFO_ENUM_INSTALLED``` and ```PK_INFO_ENUM_AVAILABLE```](https://git.gnome.org/browse/gnome-software/tree/src/plugins/packagekit-common.c#n158). I can easily add ```PK_INFO_ENUM_INSTALLING``` and ```PK_INFO_ENUM_REMOVING``` but not the other values because I have no ```AS_APP_STATE_...``` counterpart for them. Unfortunately, for all other ```PK_INFO_ENUM...``` flags ```AS_APP_STATE_UNKNOWN``` is set as the ```GsApp``` state and it will make me unable to display an info like "the application Asdf will be updated and the application Ghjkl will be reinstalled."

**Comment by hughsie** [comment]
I think we agreed a different way to do this, right?

**Comment by rluzynski** [comment]
Sorry for the delayed response, I was busy this week. To be honest, I don't understand what's wrong with my solution but also I must admit that my knowledge of AppStream and other backend stuff is minor so I am not the right person to agree or disagree. Also the fix for this issue is trivial so if you change your mind ever in future (for other reasons, maybe) you will be able to add these fields easily. In short words: please feel free to close/wontfix this issue. I'll be happy to provide more valuable contribution in future.
