### ISSUE TITLE
Does not look for AppStream metadata in /var/cache

### ISSUE THREAD

**Issue by ximion** [hughsie/appstream-glib#53]
Hi!
ASGlib should search for metadata not only in /usr/share/app-info, but also in /var/cache/app-info, as distributions which do not ship metadata via a package might install stuff there.

For reference, asxml locations are specified here: http://www.freedesktop.org/software/appstream/docs/chap-DistroData.html#spec-asxml-filenaming

Cheers,
    Matthias

**Comment by hughsie** [comment]
Using AS_STORE_LOAD_FLAG_APP_INFO_SYSTEM we do, no?

**Comment by ximion** [comment]
Yes - I am testing this with GNOME-Software, which uses this code in its AppStream plugin:
```C
ret = as_store_load (plugin->priv->store,
			     AS_STORE_LOAD_FLAG_APP_INFO_SYSTEM |
			     AS_STORE_LOAD_FLAG_APP_INFO_USER |
			     AS_STORE_LOAD_FLAG_APPDATA |
			     AS_STORE_LOAD_FLAG_DESKTOP |
			     AS_STORE_LOAD_FLAG_APP_INSTALL,
			     NULL,
			     error);
```

**Comment by hughsie** [comment]
We're using localstatedir -- did you install gnome-software/appstream-glib in a prefix or something?

**Comment by ximion** [comment]
No, but apparently asglib defines localstatedir as:
```bash
localstatedir = ${prefix}/var
```
Sure the prefix should be there? ;-)

**Comment by hughsie** [comment]
Sure, the prefix should be there; this is provided by automake.

**Comment by ximion** [comment]
Yes indeed, sorry, I was confused...
The code gets compiled with ```-DLOCALSTATEDIR=\""/var"\"```

**Comment by hughsie** [comment]
I think this is good now.
