### ISSUE TITLE
Unclear meaning of "Not enough <p> content before <ul>"

### ISSUE THREAD

**Issue by akurtakov** [hughsie/appstream-glib#57]
appstream-util validate was showing this after adding second/third p section and sentence. The real error was that there were not enough characters. It would help a lot in fixing such issues if it states clearly that there are not enough characters preferably even with the number of missing characters.

**Comment by ignatenkobrain** [comment]
validate-relax?
-- 

-Igor Gnatenko

**Comment by hughsie** [comment]
Sure, makes sense. Have you got any other suggestions? The string is in https://github.com/hughsie/appstream-glib/blob/master/libappstream-glib/as-app-validate.c if you'd like to have a go at a patch.

**Comment by kalev** [comment]
The commit above would change the error from:

```
/usr/share/appdata/eclipse.appdata.xml: FAILED:
• url-not-found         : <screenshot> url not found [http://kdaniel.fedorapeople.org/eclipsescreenshots/IDE.png]
• url-not-found         : <screenshot> url not found [http://kdaniel.fedorapeople.org/eclipsescreenshots/HELP.png]
• style-invalid         : Not enough <p> content before <ul>
Validation of files failed
```

to:

```
/usr/share/appdata/eclipse.appdata.xml: FAILED:
• url-not-found         : <screenshot> url not found [http://kdaniel.fedorapeople.org/eclipsescreenshots/IDE.png]
• url-not-found         : <screenshot> url not found [http://kdaniel.fedorapeople.org/eclipsescreenshots/HELP.png]
• style-invalid         : Content before <ul> is too short [210], at least 300 characters required
• style-invalid         : Content before <ul> is too short [63], at least 300 characters required
Validation of files failed
```

Is it any better?

**Comment by akurtakov** [comment]
Way way easier to find issue if this is the output.
