### ISSUE TITLE
Add get_* function to AsApp object that returns a hash of all metadata (fields & values)

### ISSUE THREAD

**Issue by lots0logs** [hughsie/appstream-glib#63]
Perhaps return value could be json? That would be icing on the cake :wink:

**Comment by hughsie** [comment]
What's the use-case? There is quite a lot of metadata on each object and it would be tricky to push all the translations, enum values, etc through a hash function without a lot of code.

**Comment by lots0logs** [comment]
Oh, okay. I wasn't sure whether or not it would be an easy/quick change. We're working on a front-end package management application that presents a more app-centric layout. We are combining appstream data with data from alpm and displaying it in the UI. Honestly its not a big deal,  it just would have been nice to have the option to get the data all at once instead of calling a function for each field. Admittedly, more a personal preference than anything else :wink:

**Comment by hughsie** [comment]
The problem with exporting a JSON-like blob is that it then becomes API. If you're after *everything* you could just parse the XML and convert that to an in-memory store, although obviously you'd have to handle all the fallbacks and type conversion yourself too.

What exactly are you doing that requires all the data to everything? At least in Fedora there are so many apps that trying to load all the translations of all the fields of all the apps means you've got hundreds of MBs in RSS. There are quite a few optimisations we've created like only populating the keyword cache when we perform a search to speed up startup, searching the icon path when required and that kind of thing, and so loading everything would be a huge performance regression.

**Comment by lots0logs** [comment]
That makes sense. I wasnt considering how much larger fedora repos are than Arch's. I guess I'm just trying to make the data easier to work with (we're using Python). But that's (again) not an issue so much as a personal preference. Thanks for explaining why it isn't a good idea. ..this is totally OT but I can't figure out why I'm getting this error when calling app.get_keywords() (note: it happens on a few other methods too):
```python
>>> app.get_keywords()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
TypeError: AppStreamGlib.App.get_keywords() takes exactly 2 arguments (1 given)
```
The docs say it doesnt take any arguments (though I assume 1 is the object itself) Have you seen this before? I'm using appstream 0.8.4 with appstream-glib 0.5.0

**Comment by hughsie** [comment]
You need to give the method the locale of the data you want to return, e.g. en_GB or C. The docs say:

 * @app: a #AsApp instance.
 * @locale: the locale, or %NULL. e.g. "en_GB"
