### ISSUE TITLE
asb-self-test fails

### ISSUE THREAD

**Issue by mirco** [hughsie/appstream-glib#64]
The sha1sums of the generated files data/tests/colorhug-als-2.0.*.cab don't match the hardcoded values in the test case (asb_test_firmware_func())

These are the sha1sums for the generated files on my system:
d7b9ae5b36029de606c9b047c229d9c8f5e3807c  colorhug-als-2.0.0.cab
7d4cab8775213cbd223a4a3b236618ced0af9447  colorhug-als-2.0.1.cab
6301e24ae5fb2aa73c336fd40a5d2f1835afe088  colorhug-als-2.0.2.cab

**Comment by hughsie** [comment]
What version of gcab do you have installed?

**Comment by mirco** [comment]
gcab version 0.6
