### ISSUE TITLE
CAB files within directories fail to parse

### ISSUE THREAD

**Issue by superm1** [hughsie/appstream-glib#68]
Some CAB files need to be built with all the files contained in the DriverPackage directory in order to pass the signing process.  It seems that when the CAB file is parsed the direction of the slashes get mixed up for how UNIX normally expected to parse them.

```
# G_MESSAGES_DEBUG=all appstream-util validate st.cab -v
st.cab: (appstream-util:27058): As-DEBUG: run AsStore:store-from-file
(appstream-util:27058): As-DEBUG: found file 0	DriverPackage\firmware.bin
(appstream-util:27058): As-DEBUG: found file 1	DriverPackage\firmware.inf
(appstream-util:27058): As-DEBUG: found file 2	DriverPackage\firmware.metainfo.xml
/tmp/appstream-glib-VEFE6X/DriverPackage\firmware.metainfo.xml could not be loaded: /tmp/appstream-glib-VEFE6X/DriverPackage\firmware.metainfo.xml could not be read: Failed to open file '/tmp/appstream-glib-VEFE6X/DriverPackage\firmware.metainfo.xml': No such file or directory
```

The DriverPackage\* path comes out from what gcab provides via
``` 
gcab_cabinet_extract_simple
```

**Comment by hughsie** [comment]
Hmm, could you do me a dummy example I can put in the self tests? I don't have any windows boxes available when I'm not home. I've got a fix, but want to check it works before I push. Thanks.

**Comment by superm1** [comment]
Sure, here's some dummy content put in and built with the directive that way.

Build content
https://dell.box.com/s/zosc3okgre3ekr3slqqnwfzo5on8bgxe

Directive
```
.OPTION EXPLICIT
 
.Set CabinetNameTemplate=nested_directory.cab 
 
.Set Cabinet=on
.Set Compress=on
.Set MaxDiskSize=0
.set DiskDirectoryTemplate=Bios
.set DestinationDir=DriverPackage
"firmware.bin"
"firmware.inf"
"firmware.metainfo.xml"
```

**Comment by hughsie** [comment]
Hi, your cab file didn't validate due to a typo, but it got far enough to prove it works:

    /home/hughsie/Downloads/nested_directory.cab: (lt-appstream-util:24094): As-DEBUG: run AsStore:store-from-file
    (lt-appstream-util:24094): As-DEBUG: found file 0	DriverPackage/firmware.bin
    (lt-appstream-util:24094): As-DEBUG: found file 1	DriverPackage/firmware.inf
    (lt-appstream-util:24094): As-DEBUG: found file 2	DriverPackage/firmware.metainfo.xml
    no metainfo file with provide e0f614ed-fb82-467a-a34e-71172cc07e4d

**Comment by superm1** [comment]
Yep it was a quick copy and paste hack job to make a dummy from a real, so sorry on the typo.  Feel free to adapt as needed further.
