### ISSUE TITLE
Push appdata information to bodhi

### ISSUE THREAD

**Issue by Jibec** [hughsie/appstream-glib#71]
Hi there, 

I suggested the fedora infrastructure to add more information about packages in test by using your work to gather information.

Hopefully, this should help :
 * users to make easier search
 * better appdata visibility and improvements

This enhancement has be written here : https://github.com/fedora-infra/bodhi/issues/749

You may have suggestions or knowledge about already existing prerequisites, don't hesitate to go comment.

**Comment by hughsie** [comment]
I think the other bus is fine; we can re-open this if anything new is required. I know Ralph has been using python-appstream so I hope he's working more on this stuff already.
