### ISSUE TITLE
request: "appstream-util validate" should report invalid <project_group>

### ISSUE THREAD

**Issue by cbm755** [hughsie/appstream-glib#73]
See this [fedora bug](ghttps://bugzilla.redhat.com/show_bug.cgi?id=1293561) where octave has <project_group> set to "GNU": was quite hard to track down the problem.

**Comment by carandraug** [comment]
I am bit confused by the commit that fixed this bug. Why is GNU not a valid project? Also, are you really maintaining a list of what you consider projects groups? There is a lot of them.

**Comment by hughsie** [comment]
Maybe I'm being too strict reading https://www.freedesktop.org/software/appstream/docs/chap-DistroData.html -- the idea was to have few groups here, with things like common release freezes rather than thousands of entries.

**Comment by carandraug** [comment]
Even reading the specs with such strictness, I can still imagine the list of groups to be quite large.

Here's a quick example. The [OME](http://www.openmicroscopy.org/site) project has 3 main products each of them split into separate programs and libraries, all of them distributed separately. They all use the same infrastructure and policy, bugtracker, and source control. Until 2 months ago, they would also freeze at the same time and releases and version numbers were synced. It seems to tick all the boxes for project_group. I'm in no way saying I would expect appstream to include OME on a list of recognized projects. I'm saying that such list should probably not exist.

There are project groups that are slightly more loosely organized. If only remove the requirement for  timed freezes and releases, then the number of project groups is ever larger. And GNU is one of them.

**Comment by cbm755** [comment]
To be pedantic: my original bug report here is simply that `appstream-util validate` should not say some AppData is ok, and yet it will subsequently fail.  And that has been fixed.

I filed #90 with some related wording that would've helped me when I started trying to write metainfo and appdata files.

Re: project whitelists: someone will eventually want to be in more than one...
