### ISSUE TITLE
[translations] Typo in German usage string

### ISSUE THREAD

**Issue by BenWiederhake** [hughsie/appstream-glib#76]
Currently, it responds to `appstream-util --help` in German with:

    Anwendungsoptionen:
      --nonet           Verwenden Sie keinen Netzwerkzugriff

The second line says "You shall not use the network", which is the wrong person.

I already requested translation permission on Transifex, but without this issue I would forget about this issue.

A correct phrasing looks like this:

    Anwendungsoptionen:
      --nonet           Keinen Netzwerkzugriff verwenden

Sources: I'm a native German speaker. I'm not sure whether my translation is good, but at least it's better than the current.

**Comment by hughsie** [comment]
Can you review the translations here please: https://www.transifex.com/freedesktop/appstream-glib/ Thanks!
