### ISSUE TITLE
Should support generic components

### ISSUE THREAD

**Issue by ximion** [hughsie/appstream-glib#82]
Hi!
Sinve v0.6, AppStream libraries must support generic components as valid components.
A "generic" component is basically any software which has a metainfo file but doesn't fall into the category of any other component type.
It's useful for tagging various software with useful AppStream metadata (and could highly likely replace your custom RUNTIME tag you added a while ago, since RUNTIME and GENERIC is almost the same).
See http://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#sect-Metadata-GenericComponent for reference.
(spec-wise, a generic component is what all the other component types, desktop, firmware, font, ...) derive from)
Cheers,
    Matthias

**Comment by hughsie** [comment]
I don't agree RUNTIME is the same as GENERIC. Do generic components not appear as AsApp's with type Unknown?

**Comment by ximion** [comment]
No, type Unknown only happens when somebody defined some own type which isn't present in the spec. Generic components are a known type.
Also, unknown component types are always a bug, while generic components are pretty common.

**Comment by hughsie** [comment]
ohh, so it's actually `type=generic` ?

**Comment by ximion** [comment]
Illustration:
`<component>` => type is `generic`
`<component type="generic">` => type is `generic`
`<component type="hsiubs">` => type is `unknown`

A generic component is special in that it is implied when to type is explicitly defined for a component, and that all other component types are technically derivatives of a generic component. Has been in the spec forever.
