### ISSUE TITLE
Fails when loading empty XML file

### ISSUE THREAD

**Issue by ximion** [hughsie/appstream-glib#83]
When asglib encounters an empty XML file (just a blank file, perhaps with a newline) it aborts loading any further metadata file because it can't find a root-node in that empty file.
We had this issue a while ago, would be nice to fix it again ;-)
Expected behavior would be for asglib to ignore the empty file and continue loading the remaining, likely valid data.

**Comment by hughsie** [comment]
So, I started to fix this and then I started thinking. Is a blank file really an AppStream metadata file? At the moment I get:

    cannot process file of type text/plain

Which is probably correct. Isn't the real bug the fact that something is writing empty files, without even an XML header?

**Comment by ximion** [comment]
That is also a bug - asglib stopping to load any other metadata after encountering just one broken file is the other.
I would probably make this a warning, and not a hard error.
