### ISSUE TITLE
translations tag: qt: what to do if we have no "id"?

### ISSUE THREAD

**Issue by cbm755** [hughsie/appstream-glib#88]
I went looking at the appstream-util code to see if I could figure out what to use as the `id`.  I saw this comment:

```
/* the format is ${prefix}/share/${install_dir}/translations/${id}_${locale}.qm */
```

So I assume this is the `id` referred to by `<translation type="qt">id<translation>`

But for GNU Octave:

```
# rpm -ql octave | grep qm
/usr/share/octave/4.0.0/locale/be_BY.qm
/usr/share/octave/4.0.0/locale/de_DE.qm
/usr/share/octave/4.0.0/locale/en_US.qm
/usr/share/octave/4.0.0/locale/es_ES.qm
/usr/share/octave/4.0.0/locale/fr_FR.qm
/usr/share/octave/4.0.0/locale/it_IT.qm
/usr/share/octave/4.0.0/locale/ja_JP.qm
/usr/share/octave/4.0.0/locale/nl_NL.qm
/usr/share/octave/4.0.0/locale/pt_BR.qm
/usr/share/octave/4.0.0/locale/pt_PT.qm
/usr/share/octave/4.0.0/locale/ru_RU.qm
/usr/share/octave/4.0.0/locale/uk_UA.qm
/usr/share/octave/4.0.0/locale/zh_CN.qm
```

Should I set `<translation type="qt"></translation>` in our appdata.xml?  That seems to validate---but with appstream-util version 0.5.5 so I'm not sure that's meaningful.

**Comment by cbm755** [comment]
From @hughsie's blog:

> If any app does something crazy (e.g. the eclipse system) you can always specify <lang> values in the AppData file as well, although this isn’t awesome as it requires you to manually update them.

Is this what we should do for Octave?

**Comment by hughsie** [comment]
So I guess &lt;translation&gt; is not flexible enough for octave. I'll talk to the other AppStream spec guy and work out what we should do in this case. I've got a feeling it'll involve something like &lt;translation path="share/octave/4.0.0/locale"/&gt;

**Comment by hughsie** [comment]
@ximion -- what do you think about this?

**Comment by ximion** [comment]
I think we might need a full path with substvars there, since this stuff can theoretically be named anything...
So, something like `<translation path="{datadir}/octave/4.0.0/locale/{locale}.qm"/>`
Or, alternatively, use wildcards and only one substvar to hardcode less stuff:
`<translation path="*/octave/?.0.0/locale/{locale}.qm"/>`

**Comment by hughsie** [comment]
I think anything that uses QM format has to use the locale as the filename -- I'm not sure but I think the directory has to be called "locale" as well. I think this makes sense:

    <translation path="{datadir}/octave/4.0.0"/>
    <translation path="*$PREFIX$/share/octave/*"/>

Although, the implementation of the globbing could be tricky.

**Comment by hughsie** [comment]
I believe the conclusion @ximion came to was that apps just needed to install the .qm files into the right place. I don't think we should or can support random path globs.
