### ISSUE TITLE
Stray tag not detected, even when "strict"

### ISSUE THREAD

**Issue by BenWiederhake** [hughsie/appstream-glib#94]
How to reproduce: Run `appstream-util validate-strict path/to/file.xml` on the following file:

```
<?xml version="1.0" encoding="utf-8"?>
<component type="addon">
    <id>telegram-purple</id>
    <extends>pidgin.desktop</extends>
    <name>Telegram</name>
    <summary>A plugin that adds support for Telegram</summary>
    <blah>Blah blah blah</blah>
    <url type="homepage">https://github.com/majn/telegram-purple</url>
    <url type="bugtracker">https://github.com/majn/telegram-purple/issues/</url>
    <metadata_license>GFDL-1.3</metadata_license>
    <project_license>GPL-2.0+</project_license>
    <update_contact>eischmann_at_redhat.com</update_contact>
</component>
```

Expected output: `<blah> is not a valid AppStream tag`

Actual output: None, or rather: `path/to/file.xml: OK`

I'm not sure whether this is intended, but I couldn't find any earlier discussion in the bugtracker (not even closed bugs), so I wanted to get this started.

Feel free to close this as "not a bug, works as intended".

**Comment by BenWiederhake** [comment]
For reference, the reference implementation outputs the following:

```
W - telegram-purple.metainfo.xml:telegram-purple
    Found invalid tag: 'blah'. Non-standard tags have to be prefixed with "x-".

Validation failed.
```

**Comment by hughsie** [comment]
Hey, I'm not sure about this either way. I guess it makes sense that we pick up stuff that could be a typo, but on the other hand I don't really want old versions of "appstream-util validate" to fail to validate AppData files written for a newer specification version with more fields. I guess it makes sense when running as --strict, but I'm not really sure.

**Comment by BenWiederhake** [comment]
If I were you, I'd implement that for `validate-strict`.

Still, feel free to close this as "not a bug, works as intended".
