### ISSUE TITLE
AppStream database builder uses Oxygen icons for KDE applications

### ISSUE THREAD

**Issue by colomar** [hughsie/appstream-glib#97]
The database builder currently picks up Oxygen icons for applications depending on kde-runtime. However, the current KDE icon theme is Breeze, so the applications show up with outdated icons in software centers.

**Comment by hughsie** [comment]
Can you explain a bit about the move? At the moment I explode into the extractor root the oxygen-icon-theme if a package depends on `oxygen-icon-theme` or `kde-runtime` -- should that be changed to:

* install oxygen-icon-theme when the dep is oxygen-icon-theme
* install breeze-icon-theme when the dep is kde-runtime

Thanks!

**Comment by colomar** [comment]
Good point, I just saw that kde-runtime still depends on oxygen instead of breeze, even though breeze is our default theme now. I'll investigate if we can change that.

**Comment by aleixpol** [comment]
`kde-runtime` isn't a thing since KDE Plasma 5. What code are we talking about? Fedora packaging?

**Comment by hughsie** [comment]
Yup, it's a "require" defined by quite a lot of packages in Fedora.

**Comment by hughsie** [comment]
I think this a Fedora packaging issue, not a builder issue.
